/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  RemoteStreamHandle,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ModelCatalog, SessionAttachmentRequest, SessionAttachmentValue, SessionCancelRequest, SessionCancelValue, SessionControlFrame, SessionCreateRequest, SessionCreateValue, SessionFollowFrame, SessionFollowRequest, SessionForkRequest, SessionForkValue, SessionListRequest, SessionListValue, SessionOpenWorkspacePathRequest, SessionOpenWorkspacePathValue, SessionPage, SessionPageRequest, SessionProjectionsRequest, SessionProjectionsValue, SessionPromptRequest, SessionPromptValue, SessionRenameRequest, SessionRenameValue, SessionSearchRequest, SessionSearchValue, SessionSelectModelRequest, SessionSelectModelValue, SessionUpdateQueueRequest, SessionUpdateQueueValue, SessionWorkspacePathApplication, SkillListRequest, SkillListValue } from '@deepseek-ai/dsh-api-session-controller/types'
import type { FileReferenceCandidate } from '@deepseek-ai/dsh-file-reference/types'
import type { SessionId } from '@deepseek-ai/dsh-session/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$66696c655265666572656e636573 {
    list: (agentId: SessionId, query: string, signal?: AbortSignal) => Promise<RemoteResult<FileReferenceCandidate[]>>
  }
  interface TypertRemoteNamespace$73657373696f6e {
    attachment: (request: SessionAttachmentRequest) => Promise<RemoteResult<SessionAttachmentValue>>
    cancel: (request: SessionCancelRequest) => Promise<RemoteResult<SessionCancelValue>>
    canOpenWorkspacePath: () => Promise<RemoteResult<boolean>>
    control: (signal?: AbortSignal) => RemoteStreamHandle<SessionControlFrame, never>
    create: (request: SessionCreateRequest) => Promise<RemoteResult<SessionCreateValue>>
    follow: (request: SessionFollowRequest, signal?: AbortSignal) => RemoteStreamHandle<SessionFollowFrame, never>
    fork: (request: SessionForkRequest) => Promise<RemoteResult<SessionForkValue>>
    initializeDefaultModel: () => Promise<RemoteResult<void>>
    list: (_request: SessionListRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionListValue>>
    modelCatalog: () => Promise<RemoteResult<ModelCatalog>>
    openWorkspacePath: (request: SessionOpenWorkspacePathRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionOpenWorkspacePathValue>>
    page: (request: SessionPageRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionPage>>
    projections: (request: SessionProjectionsRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionProjectionsValue>>
    prompt: (request: SessionPromptRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionPromptValue>>
    rename: (request: SessionRenameRequest) => Promise<RemoteResult<SessionRenameValue>>
    search: (request: SessionSearchRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionSearchValue>>
    selectModel: (request: SessionSelectModelRequest) => Promise<RemoteResult<SessionSelectModelValue>>
    updateQueue: (request: SessionUpdateQueueRequest) => Promise<RemoteResult<SessionUpdateQueueValue>>
    workspacePathApplications: (request: { readonly path: string; }, signal?: AbortSignal) => Promise<RemoteResult<readonly SessionWorkspacePathApplication[]>>
  }
  interface TypertRemoteNamespace$736b696c6c73 {
    list: (request: SkillListRequest, signal?: AbortSignal) => Promise<RemoteResult<SkillListValue>>
  }
  interface TypertRemoteMap {
    'fileReferences/list': (agentId: SessionId, query: string, signal?: AbortSignal) => Promise<RemoteResult<FileReferenceCandidate[]>>
    'session/attachment': (request: SessionAttachmentRequest) => Promise<RemoteResult<SessionAttachmentValue>>
    'session/cancel': (request: SessionCancelRequest) => Promise<RemoteResult<SessionCancelValue>>
    'session/canOpenWorkspacePath': () => Promise<RemoteResult<boolean>>
    'session/control': (signal?: AbortSignal) => RemoteStreamHandle<SessionControlFrame, never>
    'session/create': (request: SessionCreateRequest) => Promise<RemoteResult<SessionCreateValue>>
    'session/follow': (request: SessionFollowRequest, signal?: AbortSignal) => RemoteStreamHandle<SessionFollowFrame, never>
    'session/fork': (request: SessionForkRequest) => Promise<RemoteResult<SessionForkValue>>
    'session/initializeDefaultModel': () => Promise<RemoteResult<void>>
    'session/list': (_request: SessionListRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionListValue>>
    'session/modelCatalog': () => Promise<RemoteResult<ModelCatalog>>
    'session/openWorkspacePath': (request: SessionOpenWorkspacePathRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionOpenWorkspacePathValue>>
    'session/page': (request: SessionPageRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionPage>>
    'session/projections': (request: SessionProjectionsRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionProjectionsValue>>
    'session/prompt': (request: SessionPromptRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionPromptValue>>
    'session/rename': (request: SessionRenameRequest) => Promise<RemoteResult<SessionRenameValue>>
    'session/search': (request: SessionSearchRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionSearchValue>>
    'session/selectModel': (request: SessionSelectModelRequest) => Promise<RemoteResult<SessionSelectModelValue>>
    'session/updateQueue': (request: SessionUpdateQueueRequest) => Promise<RemoteResult<SessionUpdateQueueValue>>
    'session/workspacePathApplications': (request: { readonly path: string; }, signal?: AbortSignal) => Promise<RemoteResult<readonly SessionWorkspacePathApplication[]>>
    'skills/list': (request: SkillListRequest, signal?: AbortSignal) => Promise<RemoteResult<SkillListValue>>
  }
  interface TypertRemoteNamespaceMap {
    'fileReferences': TypertRemoteNamespace$66696c655265666572656e636573
    'session': TypertRemoteNamespace$73657373696f6e
    'skills': TypertRemoteNamespace$736b696c6c73
  }
  interface TypertRemoteScopeMap {
    'agent:fileReferences/list': (query: string, signal?: AbortSignal) => Promise<RemoteResult<FileReferenceCandidate[]>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
