/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { EncodedFileUploadRequest, FileUploadValue } from '@deepseek-ai/dsh-client-file-upload/types'
import type { SessionId } from '@deepseek-ai/dsh-session/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$66696c6555706c6f616473 {
    upload: (agentId: SessionId, request: EncodedFileUploadRequest, signal?: AbortSignal) => Promise<RemoteResult<FileUploadValue>>
  }
  interface TypertRemoteMap {
    'fileUploads/upload': (agentId: SessionId, request: EncodedFileUploadRequest, signal?: AbortSignal) => Promise<RemoteResult<FileUploadValue>>
  }
  interface TypertRemoteNamespaceMap {
    'fileUploads': TypertRemoteNamespace$66696c6555706c6f616473
  }
  interface TypertRemoteScopeMap {
    'agent:fileUploads/upload': (request: EncodedFileUploadRequest, signal?: AbortSignal) => Promise<RemoteResult<FileUploadValue>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
