/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { PluginEntryId } from '@deepseek-ai/dsh-host-plugin-inventory/types'
import type { BundleInfo, ChangeResult, InspectOptions, InstallBundleOptions, PluginInfo, PluginInstallCancellation, PluginInstallRequestId, PluginRegistries, PluginSpecInspection } from '@deepseek-ai/dsh-plugin-manager/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$706c7567696e4d616e61676572 {
    cancelInstall: (requestId: PluginInstallRequestId) => Promise<RemoteResult<PluginInstallCancellation>>
    inspect: (spec: string, options?: InspectOptions, signal?: AbortSignal) => Promise<RemoteResult<PluginSpecInspection>>
    installBundle: (spec: string, options?: InstallBundleOptions) => Promise<RemoteResult<ChangeResult>>
    listBundles: () => Promise<RemoteResult<BundleInfo[]>>
    listPlugins: () => Promise<RemoteResult<PluginInfo[]>>
    listVersionExemptions: () => Promise<RemoteResult<{ exemptions: Record<string, string[]>; warnings: string[]; }>>
    registries: () => Promise<RemoteResult<PluginRegistries>>
    removeBundle: (name: string) => Promise<RemoteResult<ChangeResult>>
    setBundleEnabled: (name: string, enabled: boolean) => Promise<RemoteResult<ChangeResult>>
    setPluginEnabled: (id: PluginEntryId, enabled: boolean) => Promise<RemoteResult<ChangeResult>>
    setVersionExemption: (packageVersion: string, runtimeVersion: string, enabled: boolean, acceptRisk?: boolean) => Promise<RemoteResult<ChangeResult>>
    waitForInstall: (requestId: PluginInstallRequestId) => Promise<RemoteResult<ChangeResult | null>>
  }
  interface TypertRemoteMap {
    'pluginManager/cancelInstall': (requestId: PluginInstallRequestId) => Promise<RemoteResult<PluginInstallCancellation>>
    'pluginManager/inspect': (spec: string, options?: InspectOptions, signal?: AbortSignal) => Promise<RemoteResult<PluginSpecInspection>>
    'pluginManager/installBundle': (spec: string, options?: InstallBundleOptions) => Promise<RemoteResult<ChangeResult>>
    'pluginManager/listBundles': () => Promise<RemoteResult<BundleInfo[]>>
    'pluginManager/listPlugins': () => Promise<RemoteResult<PluginInfo[]>>
    'pluginManager/listVersionExemptions': () => Promise<RemoteResult<{ exemptions: Record<string, string[]>; warnings: string[]; }>>
    'pluginManager/registries': () => Promise<RemoteResult<PluginRegistries>>
    'pluginManager/removeBundle': (name: string) => Promise<RemoteResult<ChangeResult>>
    'pluginManager/setBundleEnabled': (name: string, enabled: boolean) => Promise<RemoteResult<ChangeResult>>
    'pluginManager/setPluginEnabled': (id: PluginEntryId, enabled: boolean) => Promise<RemoteResult<ChangeResult>>
    'pluginManager/setVersionExemption': (packageVersion: string, runtimeVersion: string, enabled: boolean, acceptRisk?: boolean) => Promise<RemoteResult<ChangeResult>>
    'pluginManager/waitForInstall': (requestId: PluginInstallRequestId) => Promise<RemoteResult<ChangeResult | null>>
  }
  interface TypertRemoteNamespaceMap {
    'pluginManager': TypertRemoteNamespace$706c7567696e4d616e61676572
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
