import {sealVisualTrack} from '@hypit/hypit/composition';
import {projectTimelineSpace} from '@hypit/hypit/timeline';
import {browserProgram} from '@hypit/hypit/hyperframes';
const styles=o=>Object.entries(o).map(([name,value])=>({name,value}));
export function renderReveal(t,c,w,font,o){
 const unit=Math.min(c.widthPx,c.heightPx),frames=w.span.endFrameExclusive-w.span.startFrame,fps=t.frameRate.numerator/t.frameRate.denominator;
 const text=(id,value,size)=>({id,parent:'scene',kind:'text',order:['brand','title','subtitle'].indexOf(id)+1,text:value||' ',fonts:[font],style:styles({'font-size':size+'px',color:o.color,'line-height':'1.2','white-space':'pre-wrap','text-align':'center'})});
 const program=browserProgram({html:'<div class="wash"></div><div class="halo"></div><div class="content"><div class="eyebrow">{{brand}}</div><div class="rule"></div><div class="title">{{title}}</div><div class="subtitle">{{subtitle}}</div></div>',css:`:scope{overflow:hidden;pointer-events:none;background:${o.transparent?'transparent':o.background}}.wash{position:absolute;inset:-60%;background:linear-gradient(110deg,transparent 40%,${o.accent}20 50%,transparent 60%);transform:translateX(-30%)}.halo{position:absolute;width:65%;aspect-ratio:1;left:17.5%;top:50%;margin-top:-32.5%;border:1px solid ${o.accent}30;border-radius:50%}.content{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;flex-direction:column;padding:8%;gap:${unit*.032}px;box-sizing:border-box}.eyebrow{letter-spacing:${unit*.008}px}.rule{height:1px;width:${unit*.13}px;background:${o.accent};transform-origin:center}.title{letter-spacing:${unit*.002}px}.subtitle{max-width:95%;opacity:.68}`,data:{frames,fps},setup:`const title=root.querySelector('.title'),brand=root.querySelector('.eyebrow'),sub=root.querySelector('.subtitle'),rule=root.querySelector('.rule'),wash=root.querySelector('.wash'),halo=root.querySelector('.halo');const ease=x=>1-Math.pow(1-Math.max(0,Math.min(1,x)),4);return frame=>{const s=frame/data.fps,exit=Math.min(1,(data.frames-frame)/(data.fps*.35));const reveal=(el,delay,travel)=>{const p=ease((s-delay)/1.0);el.style.opacity=String(p*exit);el.style.transform='translateY('+((1-p)*travel)+'px)';};reveal(brand,.1,10);reveal(title,.38,24);reveal(sub,.85,16);const p=ease(s/1.1);rule.style.transform='scaleX('+p+')';rule.style.opacity=String(exit*.8);wash.style.transform='translateX('+(-32+s*10)+'%)';halo.style.transform='scale('+(0.91+.04*Math.min(s,4))+')';halo.style.opacity=String(p*exit*.6);};`});
 return sealVisualTrack({id:o.id,programSpaceId:projectTimelineSpace(t).id,visualIr:'hypit.visual-ir@1',presents:[{id:o.id,span:w.span,stacking:{order:o.z,tieBreak:o.id},elements:[{id:'scene',kind:'program',order:0,program,style:styles({position:'absolute',inset:0})},text('brand',o.eyebrow,unit*.032),text('title',o.title,unit*.074),text('subtitle',o.subtitle,unit*.031)]}]});
}
