/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ScheduleCatalogEntry, ScheduleDeleteRequest, ScheduleDeleteResult, ScheduleDeliveryHistoryRequest, ScheduleDeliveryHistoryResult, ScheduleListRequest, ScheduleRecord, ScheduleUpdateRequest, ScheduleUpdateResult } from '@deepseek-ai/dsh-schedule/client'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$7363686564756c65 {
    catalog: () => Promise<RemoteResult<ScheduleCatalogEntry[]>>
    delete: (request: ScheduleDeleteRequest, signal?: AbortSignal) => Promise<RemoteResult<ScheduleDeleteResult>>
    history: (request: ScheduleDeliveryHistoryRequest) => Promise<RemoteResult<ScheduleDeliveryHistoryResult>>
    list: (request: ScheduleListRequest) => Promise<RemoteResult<ScheduleRecord[]>>
    update: (request: ScheduleUpdateRequest, signal?: AbortSignal) => Promise<RemoteResult<ScheduleUpdateResult>>
  }
  interface TypertRemoteMap {
    'schedule/catalog': () => Promise<RemoteResult<ScheduleCatalogEntry[]>>
    'schedule/delete': (request: ScheduleDeleteRequest, signal?: AbortSignal) => Promise<RemoteResult<ScheduleDeleteResult>>
    'schedule/history': (request: ScheduleDeliveryHistoryRequest) => Promise<RemoteResult<ScheduleDeliveryHistoryResult>>
    'schedule/list': (request: ScheduleListRequest) => Promise<RemoteResult<ScheduleRecord[]>>
    'schedule/update': (request: ScheduleUpdateRequest, signal?: AbortSignal) => Promise<RemoteResult<ScheduleUpdateResult>>
  }
  interface TypertRemoteNamespaceMap {
    'schedule': TypertRemoteNamespace$7363686564756c65
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
