import test from 'node:test';import assert from 'node:assert/strict';import {promises as fs} from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';
import {ProjectService,run,hypit} from '../server/project.mjs';import {AudioGenerationService} from '../server/audio-generation.mjs';import {TaskRegistry} from '../server/task-registry.mjs';import {SettingsStore} from '../server/settings.mjs';
const env={ELEVENLABS_API_KEY:'private-eleven-fixture',MIMO_API_KEY:'private-mimo-fixture'};
async function fixture(t,real=false){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'frame-audio-test-')),service=new ProjectService(dir,real?undefined:async()=>{}),p=await service.create('隔离声音验证');await run('ffmpeg',['-v','error','-f','lavfi','-i','sine=frequency=440:duration=2','-y',path.join(dir,'tone.wav')]);const bytes=await fs.readFile(path.join(dir,'tone.wav'));let calls=[];const audio=new AudioGenerationService({service,getConfig:async()=>env,fetcher:async(url,o)=>{calls.push({url,body:JSON.parse(o.body)});if(url.includes('with-timestamps'))return Response.json({audio_base64:bytes.toString('base64'),alignment:{characters:['你','好'],character_start_times_seconds:[0,.5],character_end_times_seconds:[.5,1]}});if(url.includes('xiaomimimo'))return Response.json({choices:[{message:{audio:{data:bytes.toString('base64')}}}]});return new Response(bytes);}});await audio.init();t.after(async()=>{await audio.close();await fs.rm(dir,{recursive:true,force:true});});return {dir,service,p,audio,calls,bytes};}
const input=(kind='speech',extra={})=>({requestId:crypto.randomUUID(),kind,text:'你好',...extra});
const complete=async(a,id)=>{await Promise.all(a.work.values());return a.jobs.get(id);};
test('声音任务防重复，时间戳和产物进入统一任务；重启不重发',async t=>{const f=await fixture(t),req=input();const [a,b]=await Promise.all([f.audio.create(f.p.id,req),f.audio.create(f.p.id,req)]);const job=await complete(f.audio,a.id);assert.equal(a.id,b.id);assert.equal(f.calls.length,1);assert.equal(f.calls[0].body.language_code,'zh');assert.equal(f.calls[0].body.voice_settings.speed,1);assert.equal(job.status,'succeeded',job.error);assert.equal(job.alignment.characters.join(''),'你好');const registry=new TaskRegistry().register('audio',f.audio);t.after(()=>registry.close());assert.equal(registry.get(f.p.id,a.taskId).result.duration,2);assert.equal((await f.service.get(f.p.id)).assets[0].provenance.audioRole,'narration');await assert.rejects(f.audio.create(f.p.id,{...req,text:'不同文案'}),/其他声音/);const next=new AudioGenerationService({service:f.service,getConfig:async()=>({}),fetcher:()=>assert.fail('禁止外呼')});await next.init();await next.create(f.p.id,req);assert.equal(next.list(f.p.id).length,1);await next.close();assert.doesNotMatch(await fs.readFile(path.join(f.dir,'audio-generations',a.id+'.json'),'utf8'),/private-eleven|base64/);});
test('配乐/音效明确模型、时长和纯音乐；MiMo 配音设计与复用不改写台词',async t=>{const f=await fixture(t);for(const kind of ['music','sound']){const req=input(kind,{prompt:'轻快节奏',duration:6});await f.audio.create(f.p.id,req);assert.equal((await complete(f.audio,req.requestId)).status,'succeeded');}assert.equal(f.calls[0].body.force_instrumental,true);assert.equal(f.calls[0].body.music_length_ms,6000);assert.equal(f.calls[1].body.duration_seconds,6);let assetFile;for(const kind of ['speech','voice-design','voice-clone']){const req=input(kind,{provider:'mimo',prompt:'明亮热情',...(kind==='voice-clone'?{referenceFile:assetFile}:{})});await f.audio.create(f.p.id,req);const job=await complete(f.audio,req.requestId);assert.equal(job.status,'succeeded',job.error);assetFile=job.assetFile;}const sent=f.calls.slice(2);assert.equal(sent[0].body.messages.at(-1).role,'assistant');assert.equal(sent[1].body.audio.optimize_text_preview,false);assert.match(sent[2].body.audio.voice,/^data:audio\/wav;base64,/);await assert.rejects(f.audio.create(f.p.id,input('voice-clone',{referenceFile:'../../.env'})),/参考声音/);await assert.rejects(f.audio.create(f.p.id,input('sound',{duration:60,prompt:'boom'})),/时长/);});
test('未知状态不重复扣费，明确鉴权错误脱敏，落盘产物恢复只导入一次',async t=>{const f=await fixture(t);let calls=0;f.audio.fetcher=async()=>{calls++;throw Error('timeout '+env.ELEVENLABS_API_KEY);};const req=input();await f.audio.create(f.p.id,req);assert.equal((await complete(f.audio,req.requestId)).status,'unknown');await f.audio.create(f.p.id,req);assert.equal(calls,1);assert.doesNotMatch(JSON.stringify(f.audio.list(f.p.id)),/private-eleven/);f.audio.fetcher=async()=>Response.json({detail:{message:env.ELEVENLABS_API_KEY}},{status:401});const denied=input();await f.audio.create(f.p.id,denied);assert.equal((await complete(f.audio,denied.requestId)).status,'failed');assert.doesNotMatch(JSON.stringify(f.audio.list(f.p.id)),/private-eleven/);const j=f.audio.jobs.get(req.requestId);await fs.writeFile(path.join(f.audio.dir,j.id+'.mp3'),f.bytes);j.status='saving';await f.audio.persist(j);const next=new AudioGenerationService({service:f.service,getConfig:async()=>({}),fetcher:()=>assert.fail('不应重复请求')});await next.init();assert.equal(next.get(f.p.id,j.id).status,'succeeded');await next.init();assert.equal((await f.service.get(f.p.id)).assets.length,1);await next.close();});
test('旁白/配乐/音效独立编译、取段、修改、撤销，真实导出带音轨',{timeout:240000},async t=>{const f=await fixture(t,true),req=input();await f.audio.create(f.p.id,req);const job=await complete(f.audio,req.requestId);let p=await f.service.get(f.p.id);p=await f.service.change(p.id,p.revision,{type:'audio',action:'add',assetFile:job.assetFile,role:'narration',start:1,duration:1.5,trimStart:.2,fadeIn:.1,fadeOut:.2});const first=p.audioTracks[0];p=await f.service.change(p.id,p.revision,{type:'audio',action:'add',assetFile:job.assetFile,role:'music',start:0,duration:12,gain:.1,loop:true});p=await f.service.change(p.id,p.revision,{type:'audio',action:'add',assetFile:job.assetFile,role:'effect',start:5,duration:.5,gain:.4});assert.equal(p.audioTracks.length,3);p=await f.service.change(p.id,p.revision,{type:'shot',shotId:'shot-1',duration:5});assert.equal(p.audioTracks.length,3);p=await f.service.change(p.id,p.revision,{type:'audio',action:'update',trackId:first.id,gain:.7});assert.equal(p.audioTracks[0].gain,.7);p=await f.service.undo(p.id,p.revision);assert.equal(p.audioTracks[0].gain,1);await assert.rejects(f.service.change(p.id,p.revision,{type:'audio',action:'update',trackId:first.id,duration:8}),/素材时长/);
 const dir=f.service.dir(p.id),runtime=path.join(dir,'hypit.runtime.json');t.after(()=>run(hypit,['runtime','down','--workspace',dir,'--runtime',runtime,'--json'],{timeout:10000}).catch(()=>{}));const {stdout}=await run(hypit,['build',path.join(dir,'render.svrun'),'--workspace',dir,'--runtime',runtime,'--follow','--json'],{timeout:180000,maxBuffer:6e6});const result=JSON.parse(stdout),id=result.build?.id||result.buildId||result.id;const dest=path.join(f.dir,'mixed.mp4');await run(hypit,['get',id,'--output','final.video','--to',dest,'--workspace',dir,'--json'],{timeout:30000});const probe=JSON.parse((await run('ffprobe',['-v','error','-show_streams','-of','json',dest])).stdout);assert.ok(probe.streams.some(s=>s.codec_type==='audio'));assert.ok(probe.streams.some(s=>s.codec_type==='video'));});
test('新增服务配置保存为私有文件且不暴露密钥；音色中文与路由可持久化',async t=>{const f=await fixture(t),file=path.join(f.dir,'.env'),store=new SettingsStore(file);const publicResult=await store.save({elevenlabsApiKey:'test-key-eleven',mimoApiKey:'test-key-mimo',speechProvider:'mimo',mimoVoice:'苏打',elevenlabsSpeechModel:'eleven_v3',elevenlabsMusicModel:'music_v2_5',elevenlabsVoiceId:'voice-id'});assert.equal(publicResult.mimoVoice,'苏打');assert.equal(publicResult.speechProvider,'mimo');assert.doesNotMatch(JSON.stringify(publicResult),/test-key/);assert.equal((await fs.stat(file)).mode&0o777,0o600);await store.save({mimoApiKey:'',elevenlabsApiKey:''});assert.equal((await store.read()).env.MIMO_API_KEY,'test-key-mimo');assert.throws(()=>store.save({speechProvider:'untrusted'}));});

test('缩短成片裁掉越界声音而保留素材，撤销恢复完整音轨',async t=>{const f=await fixture(t),req=input();await f.audio.create(f.p.id,req);const job=await complete(f.audio,req.requestId);let p=await f.service.get(f.p.id);p=await f.service.change(p.id,p.revision,{type:'audio',action:'add',assetFile:job.assetFile,role:'music',duration:12,loop:true,fadeIn:6,fadeOut:6});p=await f.service.change(p.id,p.revision,{type:'audio',action:'add',assetFile:job.assetFile,role:'effect',start:10,duration:1});p=await f.service.change(p.id,p.revision,{type:'timeline',action:'delete',shotId:'shot-3'});assert.equal(p.duration,8);assert.equal(p.audioTracks.length,1);assert.equal(p.audioTracks[0].duration,8);assert.equal(p.audioTracks[0].fadeIn,4);assert.equal(p.assets.length,1);p=await f.service.undo(p.id,p.revision);assert.equal(p.audioTracks.length,2);assert.equal(p.audioTracks[0].duration,12);});

test('旧权限失败被后续同模型成功覆盖，英文音乐提示词不成为素材名',async t=>{
 const f=await fixture(t),now='2026-10-07T00:00:00Z';
 f.audio.jobs.set('old',{id:'old',kind:'music',provider:'elevenlabs',model:'music_v2_5',status:'failed',created:now,error:'套餐未开通'});
 const req=input('music',{text:'',prompt:'Bright upbeat instrumental',duration:6});await f.audio.create(f.p.id,req);const done=await complete(f.audio,req.requestId);assert.equal(done.status,'succeeded');
 assert.equal((await f.audio.configuration()).recentFailures.length,0);
 assert.equal(done.name,'背景配乐');assert.doesNotMatch((await f.service.get(f.p.id)).assets[0].name,/Bright/);
 f.audio.jobs.set('new',{id:'new',kind:'music',provider:'elevenlabs',model:'music_v2_5',status:'failed',created:'2099-01-01T00:00:00Z',error:'套餐未开通'});
 assert.equal((await f.audio.configuration()).recentFailures.length,1);
});
