/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  RemoteStreamHandle,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { SpeechCatalog, TranscriptionRequest } from '@deepseek-ai/dsh-experimental-api-speech-to-text/types'
import type { SpeechPreparationOptions, SpeechProviderId, SpeechSelectionPatch, Transcript } from '@deepseek-ai/dsh-experimental-speech-to-text/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$737065656368 {
    cancelPreparation: (providerId: SpeechProviderId) => Promise<RemoteResult<void>>
    catalog: () => Promise<RemoteResult<SpeechCatalog>>
    configure: (patch: SpeechSelectionPatch) => Promise<RemoteResult<void>>
    follow: (signal?: AbortSignal) => RemoteStreamHandle<SpeechCatalog, never>
    prepare: (providerId: SpeechProviderId, options?: SpeechPreparationOptions) => Promise<RemoteResult<void>>
    transcribe: (request: TranscriptionRequest, signal?: AbortSignal) => Promise<RemoteResult<Transcript>>
  }
  interface TypertRemoteMap {
    'speech/cancelPreparation': (providerId: SpeechProviderId) => Promise<RemoteResult<void>>
    'speech/catalog': () => Promise<RemoteResult<SpeechCatalog>>
    'speech/configure': (patch: SpeechSelectionPatch) => Promise<RemoteResult<void>>
    'speech/follow': (signal?: AbortSignal) => RemoteStreamHandle<SpeechCatalog, never>
    'speech/prepare': (providerId: SpeechProviderId, options?: SpeechPreparationOptions) => Promise<RemoteResult<void>>
    'speech/transcribe': (request: TranscriptionRequest, signal?: AbortSignal) => Promise<RemoteResult<Transcript>>
  }
  interface TypertRemoteNamespaceMap {
    'speech': TypertRemoteNamespace$737065656368
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
