/**
 * GENERATED by `scripts/gen-session-format-catalog.ts` — do not edit by hand.
 * The direct imports make historical readability independent of mounted plugins.
 */
import type { SessionFormatCatalogOptions } from '@deepseek-ai/dsh-session-format';
/** Static assembly shared by current reads and parent-specific historical restoration. */
export declare const sessionFormatCatalogOptions: SessionFormatCatalogOptions;
/** Physical codec dispatch and complete adjacent chain, independent of mounted plugins. */
export declare const sessionFormatCatalog: import("@deepseek-ai/dsh-session-format").SessionFormatCatalog;
//# sourceMappingURL=generated.d.ts.map