import http from 'node:http';
import net from 'node:net';
import {spawn} from 'node:child_process';
import path from 'node:path';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function freePort(){const server=net.createServer();await new Promise((ok,fail)=>server.once('error',fail).listen(0,'::1',ok));const port=server.address().port;await new Promise(r=>server.close(r));return port;}
export class StudioManager{
 constructor({service,hypit,root,prepare}){Object.assign(this,{service,hypit,root,prepare});this.sessions=new Map();this.pending=new Map();}
 request(entry,url,body,options={}){return new Promise((resolve,reject)=>{const bytes=body===undefined?null:Buffer.from(JSON.stringify(body));const req=http.request({hostname:'::1',port:entry.port,path:url,method:options.method||(bytes?'POST':'GET'),headers:{...(options.range?{range:options.range}:{}),...(bytes?{'content-type':'application/json','content-length':bytes.length}:{})}},res=>{const chunks=[];res.on('error',reject);res.on('data',x=>chunks.push(x));res.on('end',()=>resolve({status:res.statusCode,type:res.headers['content-type'],headers:res.headers,body:Buffer.concat(chunks)}));});req.on('error',reject);req.setTimeout(60000,()=>req.destroy(Error('场景编译超时')));req.end(bytes);});}
 async ensure(id){if(this.pending.has(id))return this.pending.get(id);const pending=this.start(id).finally(()=>this.pending.delete(id));this.pending.set(id,pending);return pending;}
 async start(id){const p=await this.service.get(id);await this.prepare?.(id);let e=this.sessions.get(id);if(e?.revision===p.revision&&e.child.exitCode===null&&!e.child.killed){e.used=Date.now();return e;}if(e)await this.stop(id);const port=await freePort(),dir=this.service.dir(id);const env=Object.fromEntries(['PATH','HOME','TMPDIR','HYPIT_STATE_HOME'].filter(k=>process.env[k]).map(k=>[k,process.env[k]]));const child=spawn(this.hypit,['studio','--run',path.join(dir,p.native?.run||'render.svrun'),'--workspace',dir,'--runtime',path.join(dir,'hypit.runtime.json'),'--port',String(port)],{cwd:this.root,env,stdio:['ignore','pipe','pipe']});e={id,port,child,revision:p.revision,used:Date.now(),diagnostic:''};this.sessions.set(id,e);const log=x=>e.diagnostic=(e.diagnostic+x).slice(-4000);child.stdout.on('data',log);child.stderr.on('data',log);child.on('error',log);
 for(let i=0;i<100;i++){if(child.exitCode!==null)break;try{const r=await this.request(e,'/__studio/session');if(r.status===200)return e;if(r.status>=400){const d=JSON.parse(r.body);if(d.error)e.diagnostic=String(d.error);}}catch{}await sleep(250);}await this.stop(id);throw Error('场景无法编译：'+e.diagnostic.slice(-1200));}
 async snapshot(id){for(let attempt=0;attempt<3;attempt++){const r=await this.resource(id,'/__studio/session'),p=await this.service.get(id);if(r.frameRevision!==p.revision||r.sessionPort!==this.sessions.get(id)?.port)continue;if(r.status!==200)throw Error(JSON.parse(r.body).error||'读取场景失败');const s=JSON.parse(r.body);s.revision=r.frameRevision;const labels=p.native?.labels||{};for(const track of s.tracks||[])for(const clip of track.clips||[]){const label=labels[clip.authoredId]||labels[clip.display?.title]||labels[clip.id?.split(':entity:').at(-1)];if(label)clip.display={...clip.display,title:label};}const prefix='/__studio/projects/'+id+'/';s.preview=JSON.parse(JSON.stringify(s.preview).replaceAll('/__studio/',prefix));return s;}throw Error('工程正在更新，请稍后再读取场景');}
 async mutate(id,input){const e=await this.ensure(id);if(input.revision!==e.revision)throw Error('场景已更新，请重试');const current=await this.request(e,'/__studio/session');if(current.status!==200)throw Error('无法读取场景');const r=await this.request(e,'/__studio/mutation',{...input,revision:JSON.parse(current.body).revision});const data=JSON.parse(r.body);if(r.status!==200)throw Error(data.error||'修改场景失败');return data;}
 async resource(id,url,body,options){const e=await this.ensure(id),frameRevision=e.revision,sessionPort=e.port;return {...await this.request(e,url,body,options),frameRevision,sessionPort};}
 async accept(id){const e=this.sessions.get(id);if(e)e.revision=(await this.service.get(id)).revision;}
 async currentSpace(id){const e=this.sessions.get(id);if(!e)return;const r=await this.request(e,'/__studio/session');if(r.status===200)return JSON.parse(r.body).space;}
 async stop(id){const e=this.sessions.get(id);if(!e)return;this.sessions.delete(id);if(e.child.exitCode===null){e.child.kill();await Promise.race([new Promise(r=>e.child.once('exit',r)),sleep(2000)]);}}
 close(){for(const e of this.sessions.values())e.child.kill();this.sessions.clear();}
}
