/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  RemoteStreamHandle,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ProductEvent } from '@deepseek-ai/dsh-client-product-analytics/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$70726f64756374416e616c7974696373 {
    enabled: () => Promise<RemoteResult<boolean>>
    report: (event: ProductEvent) => Promise<RemoteResult<void>>
    watchPolicy: (signal?: AbortSignal) => RemoteStreamHandle<boolean, never>
  }
  interface TypertRemoteMap {
    'productAnalytics/enabled': () => Promise<RemoteResult<boolean>>
    'productAnalytics/report': (event: ProductEvent) => Promise<RemoteResult<void>>
    'productAnalytics/watchPolicy': (signal?: AbortSignal) => RemoteStreamHandle<boolean, never>
  }
  interface TypertRemoteNamespaceMap {
    'productAnalytics': TypertRemoteNamespace$70726f64756374416e616c7974696373
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
