/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$706c7567696e526567697374727950726f6265 {
    fastest: () => Promise<RemoteResult<string | null>>
  }
  interface TypertRemoteMap {
    'pluginRegistryProbe/fastest': () => Promise<RemoteResult<string | null>>
  }
  interface TypertRemoteNamespaceMap {
    'pluginRegistryProbe': TypertRemoteNamespace$706c7567696e526567697374727950726f6265
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
