/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { SessionFeedbackRecordRequest, SessionFeedbackRecordResult } from '@deepseek-ai/dsh-command-feedback/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$73657373696f6e466565646261636b {
    record: (request: SessionFeedbackRecordRequest) => Promise<RemoteResult<SessionFeedbackRecordResult>>
  }
  interface TypertRemoteMap {
    'sessionFeedback/record': (request: SessionFeedbackRecordRequest) => Promise<RemoteResult<SessionFeedbackRecordResult>>
  }
  interface TypertRemoteNamespaceMap {
    'sessionFeedback': TypertRemoteNamespace$73657373696f6e466565646261636b
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
