import {sealVisualTrack} from '@hypit/hypit/composition';
import {projectTimelineSpace} from '@hypit/hypit/timeline';
import {browserProgram} from '@hypit/hypit/hyperframes';
const styles=o=>Object.entries(o).map(([name,value])=>({name,value}));
export function renderLayer(t,c,w,font,o,image){
 const p=o.props,kind=o.component,children=[],text=(id,content,size,color)=>{children.push({id,parent:'scene',kind:'text',order:children.length+1,text:content||' ',fonts:[font],style:styles({'font-size':size+'px','color':color,'line-height':'1.18','white-space':'pre-wrap','word-break':'break-word'})});return '{{'+id+'}}';};
 const main=text('main',p.text,p.size,p.color),sub=text('sub',p.subtitle,Math.max(16,Math.round(p.size*.43)),p.color);
 let picture='';if(image){children.push({id:'picture',parent:'scene',kind:'image',order:children.length+1,artifact:image,style:styles({width:'100%',height:'100%','object-fit':'contain'})});picture='<div class="picture">{{picture}}</div>';}
 let html=kind==='countdown'?'<div class="eyebrow">'+main+'</div><div class="digits"></div><div class="subtitle">'+sub+'</div>':kind==='product-card'?picture+'<div class="copy"><div class="headline">'+main+'</div><div class="subtitle">'+sub+'</div></div>':kind==='price'?'<div class="eyebrow">'+sub+'</div><div class="headline">'+main+'</div>':'<div class="headline">'+main+'</div><div class="subtitle">'+sub+'</div>';
 const isPanel=kind!=='title',wpx=c.widthPx*p.width/100,hpx=c.heightPx*p.height/100;
 const program=browserProgram({html:'<div class="wrap '+kind+'">'+html+'</div>',css:`:scope{overflow:visible;pointer-events:none}.wrap{position:absolute;box-sizing:border-box;left:${p.x}%;top:${p.y}%;width:${p.width}%;height:${p.height}%;padding:${isPanel?24:0}px;border-radius:22px;display:flex;flex-direction:column;justify-content:center;gap:10px;text-align:${p.align};color:${p.color};background:${isPanel?p.background:'transparent'};${isPanel?'border:1px solid #ffffff29;box-shadow:0 16px 40px #0003;':''}transform-origin:center}.headline{position:relative;z-index:1}.subtitle{opacity:.82}.title .headline{text-shadow:0 3px 22px #0009}.benefit{border-left:6px solid ${p.accent}}.price{background:${p.accent};color:${p.color}}.price .headline{letter-spacing:-2px}.eyebrow{font-size:15px;letter-spacing:2px;opacity:.7}.product-card{flex-direction:row;align-items:center;gap:22px;text-align:left}.picture{height:100%;width:40%;flex-shrink:0}.copy{flex:1;min-width:0;display:flex;flex-direction:column;gap:14px}.countdown{text-align:center;border:2px solid ${p.accent}}.digits{font-size:${Math.min(hpx*.42,wpx*.32)}px;line-height:1;font-weight:750;font-variant-numeric:tabular-nums;letter-spacing:-3px}`,data:{duration:w.span.endFrameExclusive-w.span.startFrame,fps:t.frameRate.numerator/t.frameRate.denominator,motion:p.motion,count:p.count},setup:`const el=root.querySelector('.wrap'),digits=root.querySelector('.digits');return frame=>{const a=Math.min(1,Math.max(0,frame/12)),b=Math.min(1,Math.max(0,(data.duration-frame)/7)),ease=1-Math.pow(1-a,3);el.style.opacity=String(data.motion==='none'?1:Math.min(a,b));el.style.transform=data.motion==='rise'?'translateY('+((1-ease)*36)+'px)':data.motion==='pop'?'scale('+(0.82+.18*ease)+')':'none';if(digits)digits.textContent=String(Math.max(0,Math.ceil(data.count-frame/data.fps)));};`});
 return sealVisualTrack({id:o.id,programSpaceId:projectTimelineSpace(t).id,visualIr:'hypit.visual-ir@1',presents:[{id:o.id,span:w.span,stacking:{order:p.z,tieBreak:o.id},elements:[{id:'scene',kind:'program',order:0,program,style:styles({position:'absolute',inset:0})},...children]}]});
}
