/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  RemoteStreamHandle,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ToolCallId } from '@deepseek-ai/dsh-llm/brand'
import type { SessionId } from '@deepseek-ai/dsh-session/types'
import type { AskUserQuestionAnswer } from '@deepseek-ai/dsh-user-questions/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$757365725175657374696f6e73 {
    answer: (agentId: SessionId, callId: ToolCallId, answer: AskUserQuestionAnswer) => Promise<RemoteResult<boolean>>
    attachWait: (agentId: SessionId, callId: ToolCallId, signal?: AbortSignal) => RemoteStreamHandle<{ remainingMs: number; }, never>
  }
  interface TypertRemoteMap {
    'userQuestions/answer': (agentId: SessionId, callId: ToolCallId, answer: AskUserQuestionAnswer) => Promise<RemoteResult<boolean>>
    'userQuestions/attachWait': (agentId: SessionId, callId: ToolCallId, signal?: AbortSignal) => RemoteStreamHandle<{ remainingMs: number; }, never>
  }
  interface TypertRemoteNamespaceMap {
    'userQuestions': TypertRemoteNamespace$757365725175657374696f6e73
  }
  interface TypertRemoteScopeMap {
    'agent:userQuestions/answer': (callId: ToolCallId, answer: AskUserQuestionAnswer) => Promise<RemoteResult<boolean>>
    'agent:userQuestions/attachWait': (callId: ToolCallId, signal?: AbortSignal) => RemoteStreamHandle<{ remainingMs: number; }, never>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
