/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  RemoteStreamHandle,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { TerminalAttachmentId, TerminalCreateRequest, TerminalEnvironment, TerminalFrame, TerminalRetentionFrame, TerminalShell, WebTerminalId, WebTerminalInfo } from '@deepseek-ai/dsh-api-terminal-controller/types'
import type { SessionId } from '@deepseek-ai/dsh-session/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$7465726d696e616c {
    close: (agentId: SessionId, id: WebTerminalId) => Promise<RemoteResult<void>>
    create: (agentId: SessionId, request: TerminalCreateRequest, signal?: AbortSignal) => Promise<RemoteResult<WebTerminalInfo>>
    environment: (agentId: SessionId, signal?: AbortSignal) => Promise<RemoteResult<TerminalEnvironment>>
    follow: (agentId: SessionId, id: WebTerminalId, attachmentId: TerminalAttachmentId, signal?: AbortSignal) => RemoteStreamHandle<TerminalFrame, never>
    list: (sessionId: SessionId) => Promise<RemoteResult<WebTerminalInfo[]>>
    rename: (agentId: SessionId, id: WebTerminalId, title: string) => Promise<RemoteResult<void>>
    resize: (agentId: SessionId, id: WebTerminalId, attachmentId: TerminalAttachmentId, cols: number, rows: number) => Promise<RemoteResult<void>>
    retain: (sessionId: SessionId, id: WebTerminalId, signal?: AbortSignal) => RemoteStreamHandle<TerminalRetentionFrame, never>
    shells: (agentId: SessionId, signal?: AbortSignal) => Promise<RemoteResult<TerminalShell[]>>
    write: (agentId: SessionId, id: WebTerminalId, attachmentId: TerminalAttachmentId, data: string) => Promise<RemoteResult<void>>
  }
  interface TypertRemoteMap {
    'terminal/close': (agentId: SessionId, id: WebTerminalId) => Promise<RemoteResult<void>>
    'terminal/create': (agentId: SessionId, request: TerminalCreateRequest, signal?: AbortSignal) => Promise<RemoteResult<WebTerminalInfo>>
    'terminal/environment': (agentId: SessionId, signal?: AbortSignal) => Promise<RemoteResult<TerminalEnvironment>>
    'terminal/follow': (agentId: SessionId, id: WebTerminalId, attachmentId: TerminalAttachmentId, signal?: AbortSignal) => RemoteStreamHandle<TerminalFrame, never>
    'terminal/list': (sessionId: SessionId) => Promise<RemoteResult<WebTerminalInfo[]>>
    'terminal/rename': (agentId: SessionId, id: WebTerminalId, title: string) => Promise<RemoteResult<void>>
    'terminal/resize': (agentId: SessionId, id: WebTerminalId, attachmentId: TerminalAttachmentId, cols: number, rows: number) => Promise<RemoteResult<void>>
    'terminal/retain': (sessionId: SessionId, id: WebTerminalId, signal?: AbortSignal) => RemoteStreamHandle<TerminalRetentionFrame, never>
    'terminal/shells': (agentId: SessionId, signal?: AbortSignal) => Promise<RemoteResult<TerminalShell[]>>
    'terminal/write': (agentId: SessionId, id: WebTerminalId, attachmentId: TerminalAttachmentId, data: string) => Promise<RemoteResult<void>>
  }
  interface TypertRemoteNamespaceMap {
    'terminal': TypertRemoteNamespace$7465726d696e616c
  }
  interface TypertRemoteScopeMap {
    'agent:terminal/close': (id: WebTerminalId) => Promise<RemoteResult<void>>
    'agent:terminal/create': (request: TerminalCreateRequest, signal?: AbortSignal) => Promise<RemoteResult<WebTerminalInfo>>
    'agent:terminal/environment': (signal?: AbortSignal) => Promise<RemoteResult<TerminalEnvironment>>
    'agent:terminal/follow': (id: WebTerminalId, attachmentId: TerminalAttachmentId, signal?: AbortSignal) => RemoteStreamHandle<TerminalFrame, never>
    'agent:terminal/rename': (id: WebTerminalId, title: string) => Promise<RemoteResult<void>>
    'agent:terminal/resize': (id: WebTerminalId, attachmentId: TerminalAttachmentId, cols: number, rows: number) => Promise<RemoteResult<void>>
    'agent:terminal/shells': (signal?: AbortSignal) => Promise<RemoteResult<TerminalShell[]>>
    'agent:terminal/write': (id: WebTerminalId, attachmentId: TerminalAttachmentId, data: string) => Promise<RemoteResult<void>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
