/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { OfficeToPdfGeneration, OfficeToPdfPriority, RenderedDocumentBytes } from '@deepseek-ai/dsh-office-to-pdf/types'
import type { SessionId } from '@deepseek-ai/dsh-session/types'

type RemoteDecoded<Value> = Value extends Uint8Array ? Uint8Array<ArrayBuffer>
  : Value extends string | number | boolean | null | undefined ? Value
  : { [Key in keyof Value]: RemoteDecoded<Value[Key]> }

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6f6666696365546f506466 {
    generation: (signal?: AbortSignal) => Promise<RemoteResult<OfficeToPdfGeneration>>
    render: (workspaceFileScopeId: SessionId, path: string, priority: OfficeToPdfPriority, signal?: AbortSignal) => Promise<RemoteResult<RemoteDecoded<RenderedDocumentBytes>>>
  }
  interface TypertRemoteMap {
    'officeToPdf/generation': (signal?: AbortSignal) => Promise<RemoteResult<OfficeToPdfGeneration>>
    'officeToPdf/render': (workspaceFileScopeId: SessionId, path: string, priority: OfficeToPdfPriority, signal?: AbortSignal) => Promise<RemoteResult<RemoteDecoded<RenderedDocumentBytes>>>
  }
  interface TypertRemoteNamespaceMap {
    'officeToPdf': TypertRemoteNamespace$6f6666696365546f506466
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
