/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { PermissionCatalog } from '@deepseek-ai/dsh-permission-presets/client'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$7065726d697373696f6e50726573657473 {
    catalog: () => Promise<RemoteResult<PermissionCatalog>>
  }
  interface TypertRemoteMap {
    'permissionPresets/catalog': () => Promise<RemoteResult<PermissionCatalog>>
  }
  interface TypertRemoteNamespaceMap {
    'permissionPresets': TypertRemoteNamespace$7065726d697373696f6e50726573657473
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
