const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const names={speech:'配音',music:'配乐',sound:'音效','voice-design':'设计音色','voice-clone':'复用音色'};
const roles={narration:'旁白',music:'配乐',effect:'音效'};
const status={running:'生成中',saving:'保存中',succeeded:'已完成',failed:'生成失败',unknown:'结果待确认',blocked:'保存未完成'};
export function audioTrackRows(project){return (project.audioTracks||[]).map(t=>`<div class="timeline-row audio-row"><span>${roles[t.role]}</span><div class="audio-lane"><button data-audio-track="${t.id}" style="left:${t.start/project.duration*100}%;width:${t.duration/project.duration*100}%" title="${esc(project.assets.find(a=>a.filename===t.assetFile)?.name)}">${esc(project.assets.find(a=>a.filename===t.assetFile)?.name||roles[t.role])}</button></div></div>`).join('');}
export function renderAudioInspector({el,project,onGenerate,onTrack,onAsset,onChat}){
 const audio=project.assets.filter(a=>a.kind==='audio');
 el.innerHTML=`<div class="panel-title"><h2>声音</h2><button class="secondary" data-generate>生成声音</button></div><div class="audio-inspector"><div class="audio-section-title">时间线 <span>${(project.audioTracks||[]).length} 段</span></div>${(project.audioTracks||[]).map(t=>`<button class="audio-track-card" data-edit="${t.id}"><span class="audio-role">${roles[t.role]}</span><strong>${esc(project.assets.find(a=>a.filename===t.assetFile)?.name)}</strong><small>${t.start}s — ${(t.start+t.duration).toFixed(1)}s · ${Math.round(t.gain*100)}%</small></button>`).join('')||'<p class="audio-empty">还没有独立音轨</p>'}<div class="audio-section-title">声音素材 <span>${audio.length} 个</span></div>${audio.map(a=>`<div class="audio-asset"><strong>${esc(a.name)}</strong><audio controls preload="none" src="/api/projects/${project.id}/assets/${a.filename}"></audio><div><button class="secondary" data-place="${a.filename}">加入时间线</button><button data-audio-chat="${a.filename}">交给助手</button></div></div>`).join('')||'<p class="audio-empty">生成声音或从素材库导入</p>'}</div>`;
 el.querySelector('[data-generate]').onclick=onGenerate;el.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>onTrack(b.dataset.edit));el.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>onAsset(b.dataset.place));el.querySelectorAll('[data-audio-chat]').forEach(b=>b.onclick=()=>onChat(b.dataset.audioChat));
}
export function audioTrackDialog({project,trackId,assetFile,api,onProject}){
 const track=project.audioTracks?.find(t=>t.id===trackId),asset=project.assets.find(a=>a.filename===(track?.assetFile||assetFile)),audios=project.assets.filter(a=>a.kind==='audio');if(!asset)throw Error('音频素材不存在');
 const d=document.createElement('dialog');d.className='audio-track-dialog';
 const field=(key,label,value,min=0,max=600)=>`<label>${label}<input name="${key}" aria-label="${label}" type="number" min="${min}" max="${max}" step="0.001" required value="${value}"></label>`;
 d.innerHTML=`<div class="dialog-heading"><h2>${track?'编辑声音':'加入时间线'}</h2><button class="close" aria-label="关闭声音编辑">×</button></div><form class="generation-form"><label>音频素材<select name="assetFile">${audios.map(a=>`<option value="${a.filename}" ${a===asset?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label><label>用途<select name="role" ${track?'disabled':''}>${Object.entries(roles).map(([r,n])=>`<option value="${r}" ${(track?.role||asset.provenance?.audioRole||'narration')===r?'selected':''}>${n}</option>`).join('')}</select></label><div class="audio-field-grid">${field('start','开始（秒）',track?.start||0)}${field('duration','时长（秒）',track?.duration||Math.floor(Math.min(asset.duration,project.duration)*1000)/1000,.05)}${field('trimStart','素材起点（秒）',track?.trimStart||0)}${field('gain','音量（倍）',track?.gain??(asset.provenance?.audioRole==='music'?.2:1),0,2)}${field('fadeIn','淡入（秒）',track?.fadeIn||0)}${field('fadeOut','淡出（秒）',track?.fadeOut||0)}</div><label class="checkbox-label"><input name="loop" type="checkbox" ${track?.loop?'checked':''}>循环播放</label><p class="generation-feedback" role="status"></p><div class="audio-dialog-actions">${track?'<button type="button" class="delete-audio">移除音轨</button>':''}<button type="submit" class="primary">${track?'保存修改':'添加声音'}</button></div></form>`;
 document.body.append(d);d.showModal();d.querySelector('.close').onclick=()=>d.remove();d.addEventListener('cancel',()=>d.remove());const form=d.querySelector('form'),feedback=d.querySelector('.generation-feedback');
 async function save(remove){form.querySelectorAll('button').forEach(b=>b.disabled=true);try{const change=remove?{type:'audio',action:'delete',trackId}:{type:'audio',action:track?'update':'add',...(track?{trackId}:{role:form.elements.role.value}),assetFile:form.elements.assetFile.value,...Object.fromEntries(['start','duration','trimStart','gain','fadeIn','fadeOut'].map(k=>[k,Number(form.elements[k].value)])),loop:form.elements.loop.checked};const p=await api('/api/projects/'+project.id+'/change','POST',{revision:project.revision,change});d.remove();onProject(p);}catch(e){feedback.textContent=e.message;}finally{form.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 form.onsubmit=e=>{e.preventDefault();save(false);};d.querySelector('.delete-audio')?.addEventListener('click',()=>save(true));
}
export async function audioGenerationDialog({project,api,onSettings,onAsset,onChat,onRefresh}){
 if(document.querySelector('.audio-generation-dialog'))return;const config=await api('/api/config'),d=document.createElement('dialog');d.className='audio-generation-dialog generation-dialog';
 d.innerHTML=`<div class="dialog-heading"><h2>生成声音</h2><button class="close" aria-label="关闭声音生成">×</button></div><form class="generation-form"><div class="audio-kind-switch" role="group" aria-label="声音类型">${['speech','music','sound'].map((v,i)=>`<button type="button" data-kind="${v}" class="${!i?'active':''}">${names[v]}</button>`).join('')}</div><div data-speech><label>配音服务<select name="provider"><option value="elevenlabs" ${config.speechProvider==='elevenlabs'?'selected':''}>ElevenLabs</option><option value="minimax" ${config.speechProvider==='minimax'?'selected':''}>MiniMax Speech 2.8</option><option value="mimo" ${config.speechProvider==='mimo'?'selected':''}>小米 MiMo</option></select></label><div data-eleven><label>音色<select name="voiceId" aria-label="配音音色"><option value="${esc(config.elevenlabsVoiceId)}">当前音色</option></select></label><label>语言<select name="languageCode"><option value="zh">普通话</option><option value="en">英语</option></select></label><label>语速<select name="speed"><option value="0.9">舒缓</option><option value="1" selected>自然</option><option value="1.1">轻快</option></select></label><button type="button" class="secondary" data-sample>试音</button></div><div data-minimax hidden><label>MiniMax 音色 ID<input name="minimaxVoiceId" value="${esc(config.minimaxVoiceId)}"></label><label>语速<select name="minimaxSpeed"><option value="0.9">舒缓</option><option value="1" selected>自然</option><option value="1.1">轻快</option></select></label></div><div data-mimo hidden><label>音色方式<select name="voiceMode"><option value="speech">预设音色</option><option value="voice-design">描述声音</option><option value="voice-clone">参考声音</option></select></label><label data-reference hidden>参考声音<select name="referenceFile"><option value="">选择声音素材</option>${project.assets.filter(a=>a.kind==='audio'&&/\.(mp3|wav)$/.test(a.filename)).map(a=>`<option value="${a.filename}">${esc(a.name)}</option>`).join('')}</select></label><label>声音风格<input name="style" placeholder="例如：热情、明亮，强调最后一句" maxlength="2000"></label></div><label>配音文案<textarea name="text" rows="4" maxlength="3000" placeholder="输入要说的话…"></textarea></label></div><div data-other hidden><label data-music-provider>配乐服务<select name="musicProvider"><option value="elevenlabs" ${config.musicProvider==='elevenlabs'?'selected':''}>ElevenLabs</option><option value="minimax" ${config.musicProvider==='minimax'?'selected':''}>MiniMax Music 3.0 · 历史账户</option></select></label><label>声音描述<textarea name="prompt" rows="4" maxlength="2000" placeholder="描述风格、节奏与氛围…"></textarea></label><label>时长（秒）<input name="duration" type="number" value="${Math.min(project.duration||15,180)}" min="3" max="180" step="0.1"></label></div><div class="audio-generation-footer"><button type="button" class="audio-open-settings">模型设置</button><button type="submit" class="primary">生成配音</button></div><p class="generation-feedback" role="status"></p></form><section class="audio-job-list"></section>`;
 document.body.append(d);d.showModal();const form=d.querySelector('form'),feedback=d.querySelector('.generation-feedback'),submit=form.querySelector('[type=submit]'),list=d.querySelector('.audio-job-list');let kind='speech',pending=false,timer,disposed=false,serial='',requestId=crypto.randomUUID(),request;
 const close=()=>{disposed=true;clearTimeout(timer);d.remove();};d.querySelector('.close').onclick=close;d.addEventListener('cancel',close);d.querySelector('.audio-open-settings').onclick=()=>{close();onSettings(kind==='speech'?form.elements.provider.value:kind==='music'?form.elements.musicProvider.value:'elevenlabs');};
 function update(){d.querySelector('[data-minimax]').hidden=form.elements.provider.value!=='minimax';d.querySelector('[data-music-provider]').hidden=kind!=='music';d.querySelector('[data-speech]').hidden=kind!=='speech';d.querySelector('[data-other]').hidden=kind==='speech';d.querySelector('[data-mimo]').hidden=form.elements.provider.value!=='mimo';d.querySelector('[data-eleven]').hidden=form.elements.provider.value!=='elevenlabs';d.querySelector('[data-reference]').hidden=form.elements.voiceMode.value!=='voice-clone';submit.textContent='生成'+names[kind];form.elements.duration.min=kind==='sound'?.5:3;form.elements.duration.max=kind==='sound'?30:180;if(Number(form.elements.duration.value)>Number(form.elements.duration.max))form.elements.duration.value=form.elements.duration.max;}
 d.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{if(pending)return;requestId=crypto.randomUUID();request=null;feedback.textContent='';kind=b.dataset.kind;d.querySelectorAll('[data-kind]').forEach(x=>x.classList.toggle('active',x===b));update();});form.elements.provider.onchange=update;form.elements.voiceMode.onchange=update;update();
 form.addEventListener('input',()=>{if(!pending){requestId=crypto.randomUUID();request=null;}});
 form.onsubmit=async(e,preview=false)=>{e.preventDefault();if(pending)return;const provider=kind==='speech'?form.elements.provider.value:kind==='music'?form.elements.musicProvider.value:'elevenlabs';if(!(provider==='minimax'?config.minimaxConfigured:provider==='elevenlabs'?config.elevenlabsConfigured:config.mimoConfigured)){feedback.textContent='请先在模型设置中配置 '+(provider==='minimax'?'MiniMax':provider==='mimo'?'小米 MiMo':'ElevenLabs');return;}pending=true;submit.disabled=true;feedback.textContent='';try{request??={requestId,kind:kind==='speech'&&provider==='mimo'?form.elements.voiceMode.value:kind,provider,...(kind==='speech'?{text:preview?form.elements.text.value.slice(0,64):form.elements.text.value,...(provider==='elevenlabs'?{voiceId:form.elements.voiceId.value,languageCode:form.elements.languageCode.value,speed:Number(form.elements.speed.value)}:{}),...(provider==='minimax'?{voiceId:form.elements.minimaxVoiceId.value,languageCode:'zh',speed:Number(form.elements.minimaxSpeed.value)}:{}),...(provider==='mimo'?{prompt:form.elements.style.value,referenceFile:form.elements.voiceMode.value==='voice-clone'?form.elements.referenceFile.value:''}: {})}:{prompt:form.elements.prompt.value,duration:Number(form.elements.duration.value)})};await api('/api/projects/'+project.id+'/audio','POST',request);requestId=crypto.randomUUID();request=null;await refresh();}catch(e){feedback.textContent=e.message;}finally{pending=false;submit.disabled=false;}};
 async function refresh(){clearTimeout(timer);if(!d.isConnected){disposed=true;return;}try{const jobs=await api('/api/projects/'+project.id+'/audio');if(disposed)return;const value=JSON.stringify(jobs);if(value!==serial){serial=value;list.innerHTML=jobs.slice().sort((a,b)=>b.created.localeCompare(a.created)).map(j=>`<article class="audio-job"><div><strong>${names[j.kind]} · ${j.provider==='minimax'?'MiniMax':j.provider==='mimo'?'MiMo':'ElevenLabs'}</strong><span>${status[j.status]||j.status}</span></div><p>${esc((j.text||j.prompt).slice(0,90))}</p>${j.assetFile?`<audio controls controlslist="nodownload" preload="metadata" src="/api/projects/${project.id}/assets/${j.assetFile}"></audio><div class="audio-job-actions"><button class="secondary" data-use="${j.assetFile}">加入时间线</button></div>`:j.error?`<details class="task-diagnostic"><summary>任务未完成</summary><p>${esc(j.error)}</p></details>`:''}</article>`).join('');list.querySelectorAll('[data-use]').forEach(b=>b.onclick=async()=>{await onRefresh();close();onAsset(b.dataset.use);});list.querySelectorAll('[data-chat]').forEach(b=>b.onclick=async()=>{await onRefresh();close();onChat(b.dataset.chat);});if(jobs.some(j=>j.status==='succeeded'))onRefresh();}}catch(e){if(!disposed)feedback.textContent=e.message;}finally{if(!disposed)timer=setTimeout(refresh,1800);}}
 d.querySelector('[data-sample]').onclick=e=>{if(pending)return;request=null;requestId=crypto.randomUUID();form.onsubmit(e,true);};
 if(config.elevenlabsConfigured)api('/api/audio/voices').then(voices=>{if(!d.isConnected)return;const select=form.elements.voiceId;const sorted=[...voices].sort((a,b)=>Number((b.languages||[]).includes('zh'))-Number((a.languages||[]).includes('zh')));select.innerHTML=sorted.map(v=>`<option value="${esc(v.id)}" ${v.id===config.elevenlabsVoiceId?'selected':''}>${esc(v.name)}${(v.verifiedLanguages||[]).some(l=>l.language==='zh'&&l.model===config.elevenlabsSpeechModel)?' · 中文已验证':''}</option>`).join('');}).catch(e=>{feedback.textContent=e.message;});
 await refresh();
}
