const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const labels={title:'动效标题',benefit:'卖点卡',price:'价格卡','product-card':'商品卡',countdown:'倒计时'},marks={title:'type',benefit:'list-checks',price:'tag','product-card':'shopping-bag',countdown:'timer'};
export function componentRows(project){return (project.components||[]).map(c=>`<div class="timeline-row"><span>图层</span><div class="audio-lane visual-lane"><button data-layer="${c.id}" title="${esc(c.name)}" style="left:${(c.resolved?.start||0)/project.duration*100}%;width:${Math.max(3,(c.resolved?.duration||0)/project.duration*100)}%;opacity:${c.visible?1:.4}">${esc(c.name)}</button></div></div>`).join('');}
export function renderComponents({el,project,onAdd,onEdit,onAction,onChat}){
 el.innerHTML=`<div class="panel-title"><h2>画面组件</h2></div><div class="components-panel"><div class="component-library">${(project.componentCatalog||Object.entries(labels).map(([id,name])=>({id,name}))).map(({id,name})=>`<button data-add-layer="${id}"><span class="component-mark ${id}"><i data-lucide="${marks[id]||'layers'}" aria-hidden="true"></i></span><span>${name}</span></button>`).join('')}</div><div class="audio-section-title">图层 <span>${(project.components||[]).length}</span></div><div class="component-stack">${[...(project.components||[])].sort((a,b)=>b.props.z-a.props.z).map(c=>`<article class="component-item"><button class="component-main" data-edit-layer="${c.id}"><span class="layer-dot"></span><span><strong>${esc(c.name)}</strong><small>${esc(c.props.text||labels[c.component])}</small></span></button><div class="component-item-actions"><button data-layer-action="${c.id}" data-action="visibility" aria-label="${c.visible?'隐藏':'显示'} ${esc(c.name)}">${c.visible?'隐藏':'显示'}</button><button data-layer-chat="${c.id}">交给助手</button><button data-layer-action="${c.id}" data-action="duplicate" aria-label="复制 ${esc(c.name)}">复制</button></div>${c.resolved?.error?`<p class="component-warning">${esc(c.resolved.error)}</p>`:`<p class="component-timing">${c.resolved?.start||0}s — ${((c.resolved?.start||0)+(c.resolved?.duration||0)).toFixed(1)}s · ${c.timing.kind==='absolute'?'固定时间':c.timing.kind==='shot'?'跟随镜头':c.timing.kind==='phrase'?'跟随旁白文字':'跟随声音'}</p>`}</article>`).join('')||'<p class="audio-empty">选择组件，叠加到画面</p>'}</div></div>`;
 window.lucide?.createIcons();el.querySelectorAll('[data-add-layer]').forEach(b=>b.onclick=()=>onAdd(b.dataset.addLayer));el.querySelectorAll('[data-edit-layer]').forEach(b=>b.onclick=()=>onEdit(b.dataset.editLayer));el.querySelectorAll('[data-layer-chat]').forEach(b=>b.onclick=()=>onChat(b.dataset.layerChat));el.querySelectorAll('[data-layer-action]').forEach(b=>b.onclick=()=>onAction(b.dataset.layerAction,b.dataset.action));
}
export function componentDialog({project,layerId,component,definition,onSave,onSeek}){
 const c=project.components?.find(c=>c.id===layerId),p=c?.props||{...definition?.defaults,text:'',subtitle:''},t=c?.timing||{kind:'shot',targetId:project.shots[0]?.id,offset:0,duration:3};component=c?.component||component;
 const d=document.createElement('dialog');d.className='component-dialog';const field=(name,label,value,type='text')=>`<label>${label}<input name="${name}" aria-label="${label}" type="${type}" value="${esc(value??'')}" ${type==='number'?'step="0.1"':''}></label>`;
 const select=(name,label,value,options)=>`<label>${label}<select name="${name}" aria-label="${label}">${options.map(([v,l])=>`<option value="${v}" ${v===value?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;
 d.innerHTML=`<header class="dialog-heading"><h2>${c?'编辑'+labels[component]:'添加'+labels[component]}</h2><button aria-label="关闭组件编辑">×</button></header><form><div class="component-edit-grid"><section>${field('name','图层名称',c?.name||labels[component])}<label>主文案<textarea name="text" aria-label="主文案" maxlength="100" rows="2">${esc(p.text||'')}</textarea></label>${field('subtitle','补充文案',p.subtitle)}${component==='product-card'?select('imageFile','商品图片',p.imageFile||'', [['','不使用图片'],...project.assets.filter(a=>a.kind==='image').map(a=>[a.filename,a.name])]):''}${component==='countdown'?field('count','倒数起始值',p.count||5,'number'):''}<div class="component-two">${select('motion','入场动效',p.motion||'rise',[['rise','上移淡入'],['pop','弹出'],['fade','淡入'],['none','无']])}${select('align','文字对齐',p.align||'left',[['left','左对齐'],['center','居中'],['right','右对齐']])}</div><details><summary>外观与布局</summary><div class="component-two">${[['x','横向位置 %',8],['y','纵向位置 %',16],['width','宽度 %',84],['height','高度 %',22],['size','字号',42],['z','图层顺序',50]].map(([n,l,v])=>field(n,l,p[n]??v,'number')).join('')}${field('color','文字颜色',p.color||'#FFFFFF','color')}${field('background','底色',p.background||'#181818','color')}${field('accent','强调色',p.accent||'#FF5B24','color')}</div></details></section><section class="component-time-settings"><h3>出场时间</h3>${select('kind','跟随',t.kind,[['shot','镜头'],['audio','声音片段'],['phrase','旁白中的一句话'],['absolute','固定时间']])}<div data-target></div><label data-phrase ${t.kind==='phrase'?'':'hidden'}>旁白文字<input name="phrase" value="${esc(t.phrase||'')}" placeholder="输入旁白中实际出现的文字"></label><div class="component-two">${field('offset',t.kind==='absolute'?'开始时间（秒）':'偏移（秒）',t.offset,'number')}${field('duration','显示时长（秒）',t.duration,'number')}</div>${c?.resolved?.status==='ready'?`<button type="button" class="secondary" data-preview>定位到出场画面</button>`:''}${c?.resolved?.error?`<p class="component-warning">${esc(c.resolved.error)}</p>`:''}</section></div><footer><span class="component-error" role="status"></span>${c?'<button type="button" class="remove-layer">删除图层</button>':''}<button type="submit" class="primary">${c?'保存修改':'添加到画面'}</button></footer></form>`;
 document.body.append(d);d.showModal();const form=d.querySelector('form'),close=()=>d.remove();d.querySelector('header button').onclick=close;d.addEventListener('cancel',close);
 function target(){const kind=form.elements.kind.value;d.querySelector('[data-phrase]').hidden=kind!=='phrase';d.querySelector('[data-target]').innerHTML=kind==='absolute'?'':select('targetId',kind==='shot'?'镜头':'声音片段',t.targetId,kind==='shot'?project.shots.map((s,i)=>[s.id,'镜头 '+(i+1)]):(project.audioTracks||[]).map(a=>[a.id,project.assets.find(x=>x.filename===a.assetFile)?.name||a.role]));}
 form.elements.kind.onchange=target;target();d.querySelector('[data-preview]')?.addEventListener('click',()=>{close();onSeek(c.resolved.start);});
 async function save(remove=false){const b=form.querySelector('[type=submit]');b.disabled=true;try{const data=Object.fromEntries(new FormData(form)),props={};for(const k of ['text','subtitle','imageFile','motion','align','color','background','accent'])if(data[k]!==undefined)props[k]=data[k];for(const k of ['x','y','width','height','size','z','count'])if(data[k]!==undefined)props[k]=Number(data[k]);await onSave(remove?{type:'component',action:'delete',id:layerId}:{type:'component',action:c?'update':'add',...(c?{id:layerId}:{component}),name:data.name,props,timing:{kind:data.kind,targetId:data.targetId,phrase:data.phrase,offset:Number(data.offset),duration:Number(data.duration)}});close();}catch(e){d.querySelector('.component-error').textContent=e.message;}finally{b.disabled=false;}}
 form.onsubmit=e=>{e.preventDefault();save();};d.querySelector('.remove-layer')?.addEventListener('click',()=>save(true));
}
