import {openMediaPreview} from '/media-preview.js';
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
let selectedEntity;
function displayedValue(p){if(p.control!=='number')return typeof p.value==='object'?JSON.stringify(p.value):p.value;let v=String(p.value);const suffix=[...(p.number?.suffixes||[])].sort((a,b)=>b.length-a.length).find(x=>v.endsWith(x));if(suffix)v=v.slice(0,-suffix.length);return Number((Number(v)*(p.number?.scale||1)).toPrecision(15));}

const names={'picture':'画面','titles':'字幕','mix':'声音','Audio Gain':'原声音量','spoken-captions':'逐词字幕','spoken-captions.track':'逐词字幕','shot-1-track':'镜头 1','shot-2-track':'镜头 2','shot-3-track':'镜头 3','Fit':'画面适应','Opacity':'不透明度','Blur':'模糊','Brightness':'亮度','Contrast':'对比度','Saturation':'饱和度','Playback':'播放方式','Stack Order':'叠放顺序','Clip':'裁剪','Radius':'圆角','Font Size':'字号','Active Fill':'当前词颜色','Left':'左边界','Right':'右边界','Top':'上边界','Bottom':'下边界','Text':'文字','Size':'字号','Color':'颜色','Gain':'音量','Start':'开始','Duration':'时长','Drawing order':'叠放顺序','Media':'素材','Performance':'主体画面','Sound':'原声','Caption':'字幕','Typography':'文字'};
// Hypit exposes synchronized video and its source audio as two facets of one
// authored media track. The visual inspector already owns Audio Gain; collapse
// only that exact companion, retaining independently timed audio tracks.
export function displayTracks(snapshot){
 const signature=t=>JSON.stringify(t.clips.map(c=>[c.id.split(':entity:').at(-1),c.startFrame,c.endFrameExclusive,c.band]).sort((a,b)=>String(a[0]).localeCompare(String(b[0]))));
 return snapshot.tracks.filter(t=>!(t.binding?.family==='media-audio'&&snapshot.tracks.some(v=>v.binding?.family==='media'&&v.binding.groupId===t.binding.groupId&&signature(v)===signature(t)&&v.clips.some(c=>c.inspector?.some(p=>p.label==='Audio Gain'))))).map(t=>({...t,clips:[...t.clips].sort((a,b)=>a.startFrame-b.startFrame)}));
}
const humanLabel=value=>{const s=String(value||'');return names[s]||({'copy':'广告文案','bgm-open':'配乐开场','bgm-close':'配乐收尾','sfx-power':'点亮音效','sfx-game':'游戏音效','sfx-brand':'品牌音效','bgm-bed':'背景配乐','buzz':'通知音效','open':'开罐音效','pour':'倒水音效','fizz':'气泡音效','vo-a':'旁白·前段','vo-b':'旁白·中段','vo-c':'旁白·收尾','vo':'旁白','bed':'背景配乐','ambience':'环境声','voice':'旁白','narration':'旁白','music':'配乐','captions':'字幕','title':'标题'})[s]||s.replace(/^shot[-_]?(\d+)(?:[-_].*)?$/,'镜头 $1').replace(/^scene[-_](\d+)$/,'场景 $1').replace(/^amb[-_](\d+)$/,'环境声 $1');};
const trackTitle=t=>{const label=humanLabel(t.binding?.label||t.label);return t.binding?.family==='media-audio'?label+' · 原声':label;};
const clipTitle=c=>c.display.layers?.find(l=>l.kind==='text'&&l.role==='content')?.text||humanLabel(c.display.title);
export function nativeTimeline(s){
 if(!s)return '<p>加载时间线…</p>';
 const rows=displayTracks(s).flatMap(t=>[...new Set(t.clips.map(c=>c.band||'content'))].map(band=>({label:trackTitle(t)+(band==='uses'?' · 样式':''),clips:t.clips.filter(c=>(c.band||'content')===band)})));
 return `<div class="timeline-heading"><strong>时间线</strong><span>${s.space.durationSec.toFixed(1)} 秒</span></div><div class="native-tracks">${rows.map(t=>`<div class="native-track"><span title="${esc(t.label)}">${esc(t.label)}</span><div>${t.clips.map(c=>`<button data-native-clip="${esc(c.id)}" style="left:${c.startFrame/s.space.frameCount*100}%;width:${Math.max(1,(c.endFrameExclusive-c.startFrame)/s.space.frameCount*100)}%" title="${esc(clipTitle(c))}">${esc(clipTitle(c))}</button>`).join('')}</div></div>`).join('')}</div><input id="scrub" type="range" value="0" min="0" max="${s.space.frameCount-1}" step="1" aria-label="播放位置">`;
}
export async function renderNativeInspector({el,project,snapshot,tab,api,onRefresh,onSeek,onDraft,onAudio,onImage,onVideo,onUpload}){
 if(tab==='工程'){const data=await api(`/api/projects/${project.id}/source`);if(!el.isConnected)return;el.innerHTML=`<div class="panel-title"><h2>工程文件</h2><button class="secondary" data-new-source>新建</button></div><div class="native-files">${data.files.map(f=>`<button data-source="${esc(f.path)}"><span>${esc(f.path)}</span></button>`).join('')}</div>`;el.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>sourceDialog(b.dataset.source));el.querySelector('[data-new-source]').onclick=()=>sourceDialog('');return;}
 if(tab==='素材'){
  el.innerHTML=`<div class="panel-title"><h2>素材</h2></div><div class="native-assets-actions"><button class="secondary" data-audio>生成声音</button><button class="secondary" data-image>生成图片</button><button class="secondary" data-video>生成视频</button><button class="secondary" data-import>导入素材</button><input type="file" hidden multiple data-upload accept="image/*,video/*,audio/*"></div><div class="asset-filters"><input type="search" placeholder="搜索素材" aria-label="搜索素材"><select aria-label="素材类型"><option value="">全部</option><option value="video">视频</option><option value="image">图片</option><option value="audio">音频</option><option value="selected">已采用</option><option value="superseded">历史版本</option></select></div><div class="native-files asset-library"></div>`;
  el.querySelector('[data-import]').onclick=()=>el.querySelector('[data-upload]').click();el.querySelector('[data-audio]').onclick=onAudio;el.querySelector('[data-image]').onclick=onImage;el.querySelector('[data-video]').onclick=onVideo;el.querySelector('[data-upload]').onchange=async e=>{for(const f of e.target.files)await onUpload(f);onRefresh();};
  const search=el.querySelector('[type=search]'),filter=el.querySelector('select'),list=el.querySelector('.asset-library');
  const render=()=>{const assets=project.assets.filter(a=>(!filter.value?a.editorialStatus!=='superseded':a.kind===filter.value||a.editorialStatus===filter.value)&&a.name.toLowerCase().includes(search.value.toLowerCase()));
   list.innerHTML=assets.length?assets.map(a=>{const image=a.kind==='image'?a.filename:a.poster;return `<button data-asset="${a.filename}" title="${esc(a.name)}">${image?`<img loading="lazy" src="/api/projects/${project.id}/assets/${image}" alt="">`:`<span class="asset-type-mark" aria-hidden="true"><i data-lucide="${a.kind==='audio'?'audio-lines':'film'}" aria-hidden="true"></i></span>`}<span class="asset-caption"><strong>${esc(a.name)}</strong><small>${a.scene?esc(a.scene)+' · ':''}${a.editorialStatus==='selected'?'已采用 · ':a.editorialStatus==='superseded'?'历史版本 · ':''}${esc(({image:'图片',video:'视频',audio:'音频'})[a.kind]||a.kind)}${a.duration?' · '+Number(a.duration).toFixed(1)+' 秒':''}</small></span></button>`;}).join(''):'<p class="help">没有匹配的素材</p>';
   window.lucide?.createIcons();list.querySelectorAll('[data-asset]').forEach(b=>b.onclick=()=>{const a=project.assets.find(a=>a.filename===b.dataset.asset),src=`/api/projects/${project.id}/assets/${a.filename}`;openMediaPreview({src,name:a.name,kind:a.kind,onChat:()=>onDraft('使用素材「'+a.name+'」（assets/'+a.filename+'），')});});
  };search.oninput=render;filter.onchange=render;render();return;
 }
 if(!snapshot){el.innerHTML='<div class="panel-title"><h2>场景</h2></div>';return;}
 const fps=snapshot.space.frameRate.numerator/snapshot.space.frameRate.denominator;const clips=snapshot.tracks.flatMap(t=>t.clips);let clip=clips.find(c=>c.id===selectedEntity)||clips[0];selectedEntity=clip?.id;
 el.innerHTML=`<div class="panel-title"><h2>场景</h2><span role="status" data-native-status></span></div><div class="native-scene-list">${displayTracks(snapshot).map(t=>`<section><h3>${esc(trackTitle(t))}</h3>${t.clips.map(c=>`<button data-entity="${esc(c.id)}" class="${c===clip?'chosen':''}">${esc(clipTitle(c))}<small>${(c.startFrame/snapshot.space.frameRate.numerator*snapshot.space.frameRate.denominator).toFixed(1)}s</small></button>`).join('')}</section>`).join('')}</div>${clip?`<div class="native-properties"><h3>${esc(clipTitle(clip))}</h3><button class="secondary" data-edit-chat>修改这一段</button>${(clip.editHandles||[]).filter(h=>h.enabled&&h.operation==='timeline.adjust').map(h=>`<form data-time="${h.gesture}"><label>${({'move':'移动至','trim-start':'裁剪起点','trim-end':'裁剪终点'})[h.gesture]||h.gesture} · 秒<input name="seconds" inputmode="decimal" value="${((h.gesture==='trim-end'?clip.endFrameExclusive:clip.startFrame)/fps).toFixed(2)}"></label><button type="submit">保存</button></form>`).join('')}${clip.inspector.filter(p=>p.edit&&['Text','Fit','Gain','Audio Gain','Font Size','Size','Color'].includes(p.label)).map((p,i)=>`<form data-param="${esc(p.id)}"><label>${esc(names[p.label]||p.label)}${p.options?`<select name="value">${p.options.map(o=>{const v=typeof o==='object'?o.value:o;return `<option value="${esc(v)}" ${v===p.value?'selected':''}>${esc(({'fit-width':'适应宽度','fit-height':'适应高度',native:'原始尺寸','scale-down':'仅缩小',stretch:'拉伸',none:'无',frame:'画框',rounded:'圆角',cover:'铺满',contain:'完整显示',loop:'循环',once:'播放一次',left:'左对齐',center:'居中',right:'右对齐'})[v]||(typeof o==='object'?o.label||v:v))}</option>`;}).join('')}</select>`:p.control==='boolean'?`<input name="value" type="checkbox" ${p.value?'checked':''}>`:`<input name="value" value="${esc(displayedValue(p))}" ${p.control==='number'?'inputmode="decimal"':''}>`}</label><button type="submit" aria-label="保存${esc(names[p.label]||p.label)}">保存</button></form>`).join('')}<details class="native-advanced"><summary>更多画面参数</summary>${clip.inspector.filter(p=>p.edit&&!['Text','Fit','Gain','Audio Gain','Font Size','Size','Color'].includes(p.label)).map((p,i)=>`<form data-param="${esc(p.id)}"><label>${esc(names[p.label]||p.label)}${p.options?`<select name="value">${p.options.map(o=>{const v=typeof o==='object'?o.value:o;return `<option value="${esc(v)}" ${v===p.value?'selected':''}>${esc(({'fit-width':'适应宽度','fit-height':'适应高度',native:'原始尺寸','scale-down':'仅缩小',stretch:'拉伸',none:'无',frame:'画框',rounded:'圆角',cover:'铺满',contain:'完整显示',loop:'循环',once:'播放一次',left:'左对齐',center:'居中',right:'右对齐'})[v]||(typeof o==='object'?o.label||v:v))}</option>`;}).join('')}</select>`:p.control==='boolean'?`<input name="value" type="checkbox" ${p.value?'checked':''}>`:`<input name="value" value="${esc(displayedValue(p))}" ${p.control==='number'?'inputmode="decimal"':''}>`}</label><button type="submit" aria-label="保存${esc(names[p.label]||p.label)}">保存</button></form>`).join('')}</details></div>`:''}`;
 el.querySelectorAll('[data-entity]').forEach(b=>b.onclick=()=>{selectedEntity=b.dataset.entity;const c=clips.find(c=>c.id===selectedEntity);onSeek(c.startFrame);renderNativeInspector({el,project,snapshot,tab,api,onRefresh,onSeek,onDraft,onAudio,onImage,onVideo,onUpload});});el.querySelector('[data-edit-chat]')?.addEventListener('click',()=>onDraft('只修改「'+clipTitle(clip)+'」（'+(clip.startFrame/fps).toFixed(2)+'–'+(clip.endFrameExclusive/fps).toFixed(2)+'秒）：'));
 el.querySelectorAll('[data-time]').forEach(form=>form.onsubmit=async e=>{e.preventDefault();try{const f=Math.round(Number(form.elements.seconds.value)*fps);await api(`/api/projects/${project.id}/timeline-edit`,'POST',{revision:snapshot.revision,entityId:clip.id,gesture:form.dataset.time,targetFrame:f});await onRefresh();}catch(e){const status=el.querySelector('[data-native-status]');if(status)status.textContent=e.message;}finally{form.querySelector('button').disabled=false;}});
 el.querySelectorAll('[data-param]').forEach(form=>form.onsubmit=async e=>{e.preventDefault();const save=form.querySelector('button');if(save.disabled)return;save.disabled=true;el.querySelector('[data-native-status]').textContent='保存中…';const p=clip.inspector.find(p=>p.id===form.dataset.param);const input=form.elements.value;try{const option=p.options?.find(o=>String(typeof o==='object'?o.value:o)===input.value);const value=p.control==='boolean'?input.checked:p.control==='number'?Number(input.value):option!==undefined?(typeof option==='object'?option.value:option):p.value&&typeof p.value==='object'?JSON.parse(input.value):input.value;await api(`/api/projects/${project.id}/studio-mutation`,'POST',{type:'parameter.adjust',revision:snapshot.revision,entityId:clip.id,parameterId:p.id,value});await onRefresh();}catch(e){const status=el.querySelector('[data-native-status]');if(status)status.textContent=e.message;}finally{form.querySelector('button').disabled=false;}});
 async function sourceDialog(file){const data=file?await api(`/api/projects/${project.id}/source?file=${encodeURIComponent(file)}`):{text:''};const d=document.createElement('dialog');d.className='native-source-dialog';d.innerHTML=`<header class="dialog-heading"><input aria-label="文件路径" value="${esc(file)}" placeholder="packages/my-scene/render.js"><button aria-label="关闭源码">×</button></header><textarea spellcheck="false" aria-label="工程源码">${esc(data.text)}</textarea><footer><span role="status"></span><button class="primary">保存工程</button></footer>`;document.body.append(d);d.showModal();d.addEventListener('cancel',()=>d.remove());d.querySelector('header button').onclick=()=>d.remove();d.querySelector('footer button').onclick=async()=>{const b=d.querySelector('footer button');b.disabled=true;try{await api(`/api/projects/${project.id}/source`,'POST',{revision:project.revision,files:{[d.querySelector('input').value]:d.querySelector('textarea').value}});d.remove();await onRefresh();}catch(e){d.querySelector('[role=status]').textContent=e.message;}finally{b.disabled=false;}};}
}
export function selectNativeEntity(id){selectedEntity=id;}

export function bindNativeTimeline({el,project,snapshot,api,onRefresh,onSelect,onError}){
 if(!snapshot)return;
 el.querySelectorAll('[data-native-clip]').forEach(button=>{
  const clip=snapshot.tracks.flatMap(t=>t.clips).find(c=>c.id===button.dataset.nativeClip);
  let suppress=false;
  button.onclick=()=>{if(suppress){suppress=false;return;}onSelect(clip);};
  button.onpointerdown=e=>{
   if(e.button!==0)return;
   const rect=button.getBoundingClientRect(),track=button.parentElement.getBoundingClientRect();
   const gesture=e.clientX-rect.left<7?'trim-start':rect.right-e.clientX<7?'trim-end':'move';
   if(!clip.editHandles?.some(h=>h.enabled&&h.operation==='timeline.adjust'&&h.gesture===gesture))return;
   const startX=e.clientX,original=button.style.cssText;let delta=0,dragged=false;
   button.setPointerCapture(e.pointerId);
   button.onpointermove=ev=>{if(Math.abs(ev.clientX-startX)<4&&!dragged)return;dragged=true;delta=Math.round((ev.clientX-startX)/track.width*snapshot.space.frameCount);button.style.opacity='.65';button.style.transform=`translateX(${ev.clientX-startX}px)`;};
   const finish=async ev=>{button.onpointermove=null;button.onpointerup=null;button.onpointercancel=null;button.style.cssText=original;if(button.hasPointerCapture(ev.pointerId))button.releasePointerCapture(ev.pointerId);if(!dragged||ev.type==='pointercancel')return;suppress=true;try{await api(`/api/projects/${project.id}/timeline-edit`,'POST',{revision:snapshot.revision,entityId:clip.id,gesture,targetFrame:(gesture==='trim-end'?clip.endFrameExclusive:clip.startFrame)+delta});await onRefresh();}catch(e){onError(e.message);}};
   button.onpointerup=finish;button.onpointercancel=finish;
  };
 });
}
