const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const states={preparing:'正在读取参考',analyzing:'正在拆解参考',reviewing:'正在整理改编方案',ready:'方案已就绪',failed:'分析未完成',interrupted:'分析已中断'};
const genStates={submitting:'提交中',queued:'排队中',running:'生成中',downloading:'保存中',succeeded:'已生成',failed:'生成失败',paused:'查询暂停',unknown:'提交待核对',cancelled:'已取消',expired:'已过期'};
const ratios=['16:9','9:16','4:3','3:4','1:1','21:9'];
export function openReference({project,api,onProject,initialId,onClose}){
 document.querySelector('.reference-workbench')?.dispatchEvent(new Event('frame:close'));
 const projectId=project.id,base=`/api/projects/${projectId}/references`;
 let current=null,timer,disposed=false,working=false,dirty=false,sourceDirty=false;
 const d=document.createElement('section');d.className='reference-dialog reference-workbench';d.setAttribute('aria-label','参考改编工作台');
 d.innerHTML=`<header class="reference-heading"><div><h2>参考改编</h2><span id="ref-status">从参考到你的作品</span></div><button type="button" class="close" aria-label="返回画布">×</button></header><div class="reference-layout"><aside class="reference-source"><label>参考视频<select id="ref-source" aria-label="选择参考视频"><option value="">选择视频</option>${project.assets.filter(a=>a.kind==='video').map(a=>`<option value="${a.filename}">${esc(a.name)}</option>`).join('')}</select></label><label class="secondary reference-upload">上传视频<input type="file" id="ref-upload" accept="video/mp4,video/quicktime,video/webm" hidden></label><video id="ref-player" controls playsinline hidden></video><form id="ref-form"><label>商品图<select id="ref-image"><option value="">暂不添加</option>${project.assets.filter(a=>a.kind==='image').map(a=>`<option value="${a.filename}">${esc(a.name)}</option>`).join('')}</select></label><label class="secondary reference-upload">上传商品图<input type="file" id="ref-image-upload" accept="image/png,image/jpeg" hidden></label><label>创作要求<textarea id="ref-brief" maxlength="4000" placeholder="为哪个商品改编，想保留什么？" required></textarea></label><label>借鉴重点<select id="ref-preserve"><option value="structure">结构与节奏</option><option value="style">视觉风格</option><option value="shots">构图与运镜</option></select></label><div class="reference-spec"><label>时长<input type="number" aria-label="成片时长" id="ref-duration" min="4" max="90" value="15" required></label><label>画幅<select id="ref-ratio">${ratios.map(r=>`<option>${r}</option>`).join('')}</select></label></div><button type="submit" class="secondary wide" id="ref-analyze">分析参考</button></form><details id="ref-history"><summary>参考记录</summary><div></div></details></aside><main class="reference-plan"><div id="ref-feedback" role="status"></div><div id="ref-content"><div class="reference-empty"><h3>选择一条参考视频</h3></div></div></main></div><footer class="reference-footer"><span id="ref-total"></span><div><button type="button" id="ref-save" class="secondary" hidden>保存修改</button><button type="button" id="ref-produce" class="primary" hidden>按方案制作</button></div></footer>`;
 document.querySelector('.editor').append(d);const q=s=>d.querySelector(s),all=s=>[...d.querySelectorAll(s)];
 const close=()=>{disposed=true;clearTimeout(timer);all('video').forEach(v=>v.pause());d.remove();onClose?.();};q('.close').onclick=close;d.addEventListener('frame:close',close);
 const feedback=(text,error=false)=>{q('#ref-feedback').textContent=text;q('#ref-feedback').classList.toggle('error',error);};
 const player=file=>{q('#ref-player').src=file?`/api/projects/${projectId}/assets/${file}`:'';q('#ref-player').hidden=!file;};
 const sourceChanged=()=>{sourceDirty=!!current&&(q('#ref-source').value!==current.assetFile||(q('#ref-image').value||null)!==(current.imageFile||null)||q('#ref-brief').value.trim()!==current.brief||q('#ref-preserve').value!==(current.preserve||'structure')||Number(q('#ref-duration').value)!==current.targetDuration);q('#ref-analyze').textContent=current?'重新分析':'分析参考';q('#ref-produce').disabled=sourceDirty;q('#ref-save').disabled=sourceDirty;feedback(sourceDirty?'输入已修改，重新分析后再制作。':'');};
 q('#ref-source').onchange=()=>{player(q('#ref-source').value);sourceChanged();};
 for(const id of ['ref-image','ref-brief','ref-preserve','ref-duration'])q('#'+id).addEventListener('input',sourceChanged);
 q('#ref-ratio').onchange=()=>{if(current){dirty=true;q('#ref-save').hidden=false;}};
 function setBusy(value){working=value;all('button').filter(b=>!b.classList.contains('close')).forEach(b=>b.disabled=value);if(!value){q('#ref-produce').disabled=sourceDirty;q('#ref-save').disabled=sourceDirty;}}
 async function guard(fn){if(working)return;setBusy(true);feedback('');try{await fn();}catch(e){feedback(e.message,true);}finally{if(!disposed)setBusy(false);}}
 async function upload(file,kind){if(!file)return;await guard(async()=>{const r=await fetch(`/api/projects/${projectId}/assets`,{method:'POST',headers:{'X-Filename':encodeURIComponent(file.name)},body:file});const a=await r.json();if(!r.ok)throw Error(a.error);project=await api('/api/projects/'+projectId);await onProject(project);const select=q(kind==='video'?'#ref-source':'#ref-image'),o=document.createElement('option');o.value=a.filename;o.textContent=a.name;select.append(o);select.value=a.filename;if(kind==='video'){player(a.filename);if(!current&&a.width&&a.height)q('#ref-ratio').value=ratios.reduce((b,r)=>Math.abs(r.split(':')[0]/r.split(':')[1]-a.width/a.height)<Math.abs(b.split(':')[0]/b.split(':')[1]-a.width/a.height)?r:b,'16:9');}sourceChanged();});}
 q('#ref-upload').onchange=e=>upload(e.target.files[0],'video');q('#ref-image-upload').onchange=e=>upload(e.target.files[0],'image');
 q('#ref-form').onsubmit=e=>{e.preventDefault();guard(async()=>{if(!q('#ref-source').value)throw Error('请先添加参考视频');current=await api(base,'POST',{requestId:crypto.randomUUID(),assetFile:q('#ref-source').value,imageFile:q('#ref-image').value||null,brief:q('#ref-brief').value,targetDuration:Number(q('#ref-duration').value),ratio:q('#ref-ratio').value,preserve:q('#ref-preserve').value});dirty=false;sourceDirty=false;render();schedule();await loadHistory();});};
 function readPlan(){const plan=structuredClone(current.plan);all('[data-scene]').forEach(el=>{const s=plan.scenes[Number(el.dataset.scene)];for(const key of ['role','prompt','voiceover','caption','duration'])s[key]=key==='duration'?Number(el.querySelector(`[name="${key}"]`).value):el.querySelector(`[name="${key}"]`).value;const picture=el.querySelector('[name="sceneImage"]').value;if(picture)s.imageFile=picture;else delete s.imageFile;const source=el.querySelector('[name="sourceVideo"]').value;if(source==='auto')delete s.useSourceVideo;else s.useSourceVideo=source==='yes';});return plan;}
 async function save(){if(sourceDirty)throw Error('请先重新分析修改后的输入');if(!dirty)return;current=await api(base+'/'+current.id+'/plan','POST',{version:current.version,plan:readPlan(),ratio:q('#ref-ratio').value});dirty=false;render();}
 q('#ref-save').onclick=()=>guard(async()=>{await save();feedback('修改已保存');});
 q('#ref-produce').onclick=()=>guard(async()=>{await save();const latest=await api('/api/projects/'+projectId);await api(base+'/'+current.id+'/produce','POST',{revision:latest.revision,version:current.version,resume:!!current.production});await onProject(await api('/api/projects/'+projectId));close();});
 function render(){if(disposed||!current)return;if(!sourceDirty)q('#ref-duration').value=current.targetDuration||15;q('#ref-status').textContent=current.phase||states[current.status]||current.status;q('#ref-total').textContent='';q('#ref-save').hidden=!dirty;q('#ref-produce').hidden=current.status!=='ready';
  if(current.status!=='ready'){q('#ref-content').innerHTML=`<div class="reference-empty"><span>${['preparing','analyzing','reviewing'].includes(current.status)?'<i class="reference-spinner"></i>':''}${esc(current.phase||states[current.status])}</span><h3>${esc(current.assetName)}</h3>${current.error?`<details><summary>查看原因</summary><p>${esc(current.error)}</p></details>`:''}${['failed','interrupted'].includes(current.status)?'<button id="ref-retry" class="secondary">重新分析</button>':''}</div>`;q('#ref-retry')?.addEventListener('click',()=>guard(async()=>{current=await api(base+'/'+current.id+'/retry','POST',{});render();schedule();}));return;}
  const total=current.plan.scenes.reduce((n,s)=>n+s.duration,0);q('#ref-total').textContent=`${total} 秒 · ${q('#ref-ratio').value}`;q('#ref-produce').textContent=current.production?'继续制作':'按方案制作';q('#ref-analyze').textContent='重新分析';
  q('#ref-content').innerHTML=`<section class="reference-summary"><h3>改编方案</h3><p>${esc(current.plan.summary)}</p><details><summary>声音与待核对项</summary>${current.analysisMethod==='frame-review'?'<p>分析方式：关键帧观察</p>':current.analysisMethod==='frames-transcript'?'<p>分析依据：时间戳画面与语音转录</p>':''}<p>${esc(current.plan.audio)}</p><p>${esc(current.plan.uncertainties||'')}</p></details></section><div class="reference-scenes">${current.plan.scenes.map((s,i)=>{const j=current.jobs?.findLast(j=>j.sceneId?j.sceneId===s.id:j.index===i),g=current.generations?.find(g=>g.id===j?.jobId);return `<section class="reference-scene" data-scene="${i}"><div class="reference-scene-header"><span>${String(i+1).padStart(2,'0')}</span><input name="role" aria-label="第 ${i+1} 段作用" value="${esc(s.role)}" maxlength="60"><label><input name="duration" aria-label="第 ${i+1} 段时长" type="number" min="0.5" max="15" step="any" value="${s.duration}"> 秒</label></div><div class="reference-comparison"><div class="reference-evidence"><small>原片</small><button type="button" class="ref-seek" data-time="${s.sourceStart}" title="播放这段参考"><img src="${base}/${current.id}/scene-${i}.jpg" alt="原片参考画面"><span>${s.sourceStart.toFixed(1)}–${s.sourceEnd.toFixed(1)}s</span></button><p>${esc(s.observation)}</p></div><div class="reference-adaptation"><small>你的新片</small><label><textarea name="prompt" aria-label="第 ${i+1} 段画面" maxlength="2000">${esc(s.prompt)}</textarea></label><p>${esc(s.preserve)}</p></div></div><details class="reference-copy-details"><summary>镜头参考</summary><div class="reference-copy"><label>商品与关键帧<select name="sceneImage" aria-label="第 ${i+1} 段商品图"><option value="">使用项目商品图</option>${project.assets.filter(a=>a.kind==='image').map(a=>`<option value="${a.filename}" ${s.imageFile===a.filename?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label><label>视频参考<select name="sourceVideo" aria-label="第 ${i+1} 段视频参考"><option value="auto" ${s.useSourceVideo===undefined?'selected':''}>跟随借鉴重点</option><option value="yes" ${s.useSourceVideo===true?'selected':''}>使用这段原片</option><option value="no" ${s.useSourceVideo===false?'selected':''}>仅采用分析与图片</option></select></label></div></details><details class="reference-copy-details"><summary>旁白与字幕</summary><div class="reference-copy"><label>旁白<textarea name="voiceover" aria-label="第 ${i+1} 段配音" maxlength="200">${esc(s.voiceover)}</textarea></label><label>字幕<input name="caption" aria-label="第 ${i+1} 段字幕" maxlength="70" value="${esc(s.caption)}"></label></div></details>${g?`<div class="reference-job"><span>${esc(genStates[g.status]||g.status)}</span>${g.assetFile?`<video controls preload="none" src="/api/projects/${projectId}/assets/${g.assetFile}"></video>`:''}${g.error?`<details><summary>查看原因</summary><p>${esc(g.error)}</p></details>`:''}</div>`:''}</section>`;}).join('')}</div><details class="reference-production-note"><summary>制作范围与用量</summary><p>${current.plan.scenes.length} 段视频，按方案完成旁白、连续配乐、字幕和导出。使用模型设置中的默认服务，按服务商实际用量计费；已完成的素材优先复用。</p></details>`;
  all('.ref-seek').forEach(b=>b.onclick=()=>{q('#ref-player').currentTime=Number(b.dataset.time);q('#ref-player').play().catch(()=>{});});all('[data-scene] input,[data-scene] textarea,[data-scene] select').forEach(el=>el.oninput=()=>{dirty=true;q('#ref-save').hidden=false;});
 }
 function schedule(){clearTimeout(timer);timer=setTimeout(async()=>{if(disposed||!d.isConnected){close();return;}if(working||dirty||sourceDirty){schedule();return;}try{if(current){const latest=await api(base+'/'+current.id);if(disposed)return;if(JSON.stringify(latest)!==JSON.stringify(current)){current=latest;render();await loadHistory();}}schedule();}catch(e){feedback(e.message,true);schedule();}},3000);}
 async function select(item){current=item;dirty=false;sourceDirty=false;q('#ref-source').value=item.assetFile;player(item.assetFile);q('#ref-image').value=item.imageFile||'';q('#ref-brief').value=item.brief;q('#ref-duration').value=item.targetDuration||15;q('#ref-ratio').value=item.ratio||'9:16';q('#ref-preserve').value=item.preserve||'structure';render();schedule();}
 async function loadHistory(){const list=(await api(base)).filter(x=>x.purpose!=='quality');if(disposed)return;q('#ref-history div').innerHTML=list.map(x=>`<button type="button" data-reference="${x.id}"><span>${esc(x.assetName)}</span><small>${esc(states[x.status])}</small></button>`).join('');all('[data-reference]').forEach(b=>b.onclick=()=>guard(async()=>{if(dirty||sourceDirty)throw Error('请先保存修改或重新分析');await select(list.find(x=>x.id===b.dataset.reference));}));if(!current&&list.length)await select(list.find(x=>x.id===initialId)||list[0]);}
 loadHistory().catch(e=>feedback(e.message,true));return close;
}
