/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  RemoteStreamHandle,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { JobFollowFrame, JobFollowRequest, JobKillRequest, JobKillValue, JobListFrame, JobListRequest } from '@deepseek-ai/dsh-api-job-controller/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6a6f62 {
    follow: (request: JobFollowRequest, signal?: AbortSignal) => RemoteStreamHandle<JobFollowFrame, never>
    kill: (request: JobKillRequest) => Promise<RemoteResult<JobKillValue>>
    list: (request: JobListRequest, signal?: AbortSignal) => RemoteStreamHandle<JobListFrame, never>
  }
  interface TypertRemoteMap {
    'job/follow': (request: JobFollowRequest, signal?: AbortSignal) => RemoteStreamHandle<JobFollowFrame, never>
    'job/kill': (request: JobKillRequest) => Promise<RemoteResult<JobKillValue>>
    'job/list': (request: JobListRequest, signal?: AbortSignal) => RemoteStreamHandle<JobListFrame, never>
  }
  interface TypertRemoteNamespaceMap {
    'job': TypertRemoteNamespace$6a6f62
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
