/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  RemoteStreamHandle,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { AccountBonusBatch, AccountBonusOrderId, AccountClientMetadata, AccountDetails, AccountUserId, AccountView, SignInAttemptId } from '@deepseek-ai/dsh-deepseek-account/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6163636f756e74 {
    ackBonusNotified: (accountId: AccountUserId, orderId: AccountBonusOrderId, client: AccountClientMetadata) => Promise<RemoteResult<boolean>>
    cancelSignIn: (attemptId: SignInAttemptId) => Promise<RemoteResult<AccountView>>
    getBalance: (client: AccountClientMetadata) => Promise<RemoteResult<AccountDetails['balance'] | null>>
    getProfile: (client: AccountClientMetadata) => Promise<RemoteResult<AccountDetails['profile'] | null>>
    getState: () => Promise<RemoteResult<AccountView>>
    getUnnotifiedBonuses: (client: AccountClientMetadata) => Promise<RemoteResult<AccountBonusBatch | null>>
    hasRunningAccountTasks: () => Promise<RemoteResult<boolean>>
    signOut: (client: AccountClientMetadata) => Promise<RemoteResult<AccountView>>
    startSignIn: (client: AccountClientMetadata, callbackOrigin: string, loginSource: 'web' | 'desktop') => Promise<RemoteResult<AccountView>>
    watch: (signal?: AbortSignal) => RemoteStreamHandle<AccountView, never>
    watchExpiry: (signal?: AbortSignal) => RemoteStreamHandle<'session-expired', never>
  }
  interface TypertRemoteMap {
    'account/ackBonusNotified': (accountId: AccountUserId, orderId: AccountBonusOrderId, client: AccountClientMetadata) => Promise<RemoteResult<boolean>>
    'account/cancelSignIn': (attemptId: SignInAttemptId) => Promise<RemoteResult<AccountView>>
    'account/getBalance': (client: AccountClientMetadata) => Promise<RemoteResult<AccountDetails['balance'] | null>>
    'account/getProfile': (client: AccountClientMetadata) => Promise<RemoteResult<AccountDetails['profile'] | null>>
    'account/getState': () => Promise<RemoteResult<AccountView>>
    'account/getUnnotifiedBonuses': (client: AccountClientMetadata) => Promise<RemoteResult<AccountBonusBatch | null>>
    'account/hasRunningAccountTasks': () => Promise<RemoteResult<boolean>>
    'account/signOut': (client: AccountClientMetadata) => Promise<RemoteResult<AccountView>>
    'account/startSignIn': (client: AccountClientMetadata, callbackOrigin: string, loginSource: 'web' | 'desktop') => Promise<RemoteResult<AccountView>>
    'account/watch': (signal?: AbortSignal) => RemoteStreamHandle<AccountView, never>
    'account/watchExpiry': (signal?: AbortSignal) => RemoteStreamHandle<'session-expired', never>
  }
  interface TypertRemoteNamespaceMap {
    'account': TypertRemoteNamespace$6163636f756e74
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
